<Project>
  <PropertyGroup Condition="'$(IsPackable)' == 'true' and '$(PackageReadmeFile)' == ''">
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <MptUseCommonPackageReadme>true</MptUseCommonPackageReadme>
  </PropertyGroup>

  <ItemGroup Condition="'$(MptUseCommonPackageReadme)' == 'true'">
    <None Include="$(MSBuildThisFileDirectory)docs\sdk\README.md"
          Pack="true"
          PackagePath="README.md"
          Visible="false" />
  </ItemGroup>
</Project>
