<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NssmManager.Contracts\NssmManager.Contracts.csproj" />
    <ProjectReference Include="..\NssmManager.Compatibility\NssmManager.Compatibility.csproj" />
    <ProjectReference Include="..\NssmManager.Windows\NssmManager.Windows.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NssmManager.Tests" />
  </ItemGroup>
</Project>
