<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LocalLagCleaner.Tool</AssemblyName>
    <RootNamespace>LocalLagCleaner.Tool</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MyPowerTools.AvaloniaSdk" Version="0.2.0" />
    <PackageReference Include="MyPowerTools.ToolSdk" Version="0.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LocalLagCleaner.Core\LocalLagCleaner.Core.csproj" />
  </ItemGroup>
</Project>
