'use strict';
const paths={cloud:'M6 18h12a4 4 0 0 0 0-8h-1a5 5 0 0 0-9.7-1.7A5 5 0 0 0 6 18Z',chat:'M5 4h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H9l-5 3v-3H3V6a2 2 0 0 1 2-2Z M8 9h8 M8 13h5',folder:'M3 7V5h7l2 2h9v13H3V7Z',plus:'M12 5v14 M5 12h14',chevron:'m9 6 6 6-6 6',back:'m14 6-6 6 6 6',close:'m6 6 12 12 M18 6 6 18',check:'m5 12 4 4L19 6',shield:'m12 3 8 3v6c0 4-4 7-8 9-4-2-8-5-8-9V6l8-3Z m-4 9 3 3 5-6',lock:'M6 10h12v11H6V10Z M8 10V7a4 4 0 0 1 8 0v3',more:'M5 12h.01 M12 12h.01 M19 12h.01',info:'M12 16v-4 M12 8h.01 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z',arrow:'M5 12h14 m-5-5 5 5-5 5',pc:'M3 4h18v13H3V4Z M8 21h8 M12 17v4',route:'M5 5h6a5 5 0 0 1 0 10H5 m4-4-4 4 4 4 M15 5h4',clock:'M12 7v5l3 2 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z',broom:'m14 3-4 9 M7 11l8 3-4 8-9-4 5-7Z M5 17l6 3',pause:'M8 5v14 M16 5v14',play:'m8 4 12 8-12 8V4Z',logout:'M9 4H4v16h5 M8 12h13 m-5-5 5 5-5 5',file:'M5 3h9l5 5v13H5V3Z M14 3v6h5 M9 13h6 M9 17h5',warning:'m12 3 10 18H2L12 3Z M12 9v5 M12 17h.01',refresh:'M20 11a8 8 0 0 0-14-5L3 9 M3 4v5h5 M4 13a8 8 0 0 0 14 5l3-3 M21 20v-5h-5',external:'M14 3h7v7 M21 3 9 15 M10 5H4v15h15v-6',gear:'m9 3 6 0 1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1 1-3Z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z'};
const icon=(name,css='')=>`<svg class="${css}" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.cloud}"/></svg>`;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const providers={ali:{name:'阿里云盘',nickname:'小林的阿里云盘',initial:'阿',capacity:'1 TB',used:'128 GB',percent:13},baidu:{name:'百度网盘',nickname:'小林的百度网盘',initial:'百',capacity:'2 TB',used:'256 GB',percent:13}};
const $=selector=>document.querySelector(selector);
const htmlButton=(action,text,css='primary',id='')=>`<button class="${css}" data-action="${action}"${id?` data-id="${esc(id)}"`:''}>${text}</button>`;
const providerIcon=(id,large=false)=>`<span class="provider-icon ${id==='baidu'?'baidu':''} ${large?'large':''}">${icon('cloud')}</span>`;
let state,view='cloud',previewMode='desktop',activeAccount=null,authContext=null,browse='',generation=0,toastTimer,returnFocus=null,attachment=false,chatDraft='',messages=[];
const fresh=()=>({accounts:[{id:'ali-main',provider:'ali',nickname:'小林',folder:'MPT',status:'connected',percent:13,used:'128 GB',space:'896 GB'}],defaultId:'ali-main',policy:'auto',cleanup:'manual',scenario:'normal'});
function persist(){try{localStorage.setItem('mpt-cloud-v4',JSON.stringify(state))}catch{}}
function getAccount(id=activeAccount){return state.accounts.find(a=>a.id===id)}
function defaultAccount(){return getAccount(state.defaultId)}
function usableAccount(){const account=defaultAccount();return account?.status==='connected'?account:null}
function closeDialog(){generation++;$('#dialog').close();if(returnFocus?.isConnected)returnFocus.focus();else $('#main').focus({preventScroll:true})}
function notify(message){const d=$('#dialog');if(d.open){let note=d.querySelector('.modal-status');if(!note){note=document.createElement('p');note.className='info-block modal-status';note.setAttribute('role','status');d.querySelector('.dialog-body').append(note)}note.textContent=message;note.scrollIntoView({block:'nearest'});return}const t=$('#toast');t.textContent=message;t.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.hidden=true,3200)}
function modal(title,body,footer=''){generation++;const d=$('#dialog');if(!d.open)returnFocus=document.activeElement;$('#dialog-content').innerHTML=`<header class="dialog-head"><h2 id="dialog-title">${title}</h2><button class="iconbtn" data-action="close" aria-label="关闭">${icon('close')}</button></header><div class="dialog-body">${body}</div>${footer?`<footer class="dialog-foot">${footer}</footer>`:''}`;if(!d.open)d.showModal();d.querySelector('button')?.focus({preventScroll:true})}
function setMode(mode){previewMode=mode;$('#app').classList.toggle('phone',mode==='phone');document.querySelectorAll('[data-action=viewport]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.value===mode)))}
function mobile(){return previewMode==='phone'||matchMedia('(max-width:760px)').matches}
function scenario(name){closeDialog();state=fresh();state.scenario=name;if(name==='empty'){state.accounts=[];state.defaultId=null}else if(name==='expired')state.accounts[0].status='expired';else if(name==='full'){Object.assign(state.accounts[0],{status:'full',space:'12 MB',used:'接近 1 TB',percent:99.99,remainingMB:12})}view='cloud';messages=[];attachment=false;chatDraft='';persist();render()}
function accountStatus(a){return a.status==='expired'?'需要重新登录':a.status==='full'?'空间不足':a.status==='paused'?'已暂停':'已连接'}
function folderLabel(a){return a.folder==='MPT'?'MPT 专用文件夹':a.folder}
function accountCard(a){const p=providers[a.provider];return `<article class="account"><div class="account-top">${providerIcon(a.provider)}<div class="account-name"><div class="account-title"><h3>${p.name}</h3>${state.defaultId===a.id?'<span class="badge">默认中转盘</span>':''}</div><p>${esc(a.nickname)} · 仅这台设备</p></div><button class="iconbtn" data-action="manage" data-id="${a.id}" aria-label="管理${p.name}">${icon('more')}</button></div><div class="capacity"><div class="capacity-copy"><span class="status ${a.status!=='connected'?'warn':''}"><i class="dot"></i>${accountStatus(a)}</span><span>${a.status==='expired'?'重新登录后更新空间':a.status==='full'||Number.isFinite(a.remainingMB)?'剩余 '+a.space:'已用 '+a.used+' / '+p.capacity}</span></div><div class="meter ${a.status==='full'?'warning':''}"><i style="width:${a.percent}%"></i></div></div><div class="account-bottom"><button class="folder-inline" data-action="folder" data-id="${a.id}">${icon('folder')}<span>${esc(folderLabel(a))}</span>${icon('chevron','arrow')}</button>${a.status==='expired'?htmlButton('reauth','重新登录','textbtn',a.id):a.status==='full'?htmlButton('cleanup-now','释放空间','textbtn',a.id):a.status==='paused'?htmlButton('resume','恢复使用','textbtn',a.id):htmlButton('manage','管理','textbtn',a.id)}</div></article>`}
function setting(action,title,sub,value,ico){return `<button class="setting-row" data-action="${action}"><span class="setting-icon">${icon(ico)}</span><span class="setting-copy"><b>${title}</b><small>${sub}</small></span><span class="setting-value">${value}</span>${icon('chevron','arrow')}</button>`}
function issueBanner(){const a=defaultAccount();if(!a)return state.policy==='cloud'?`<div class="alert"><div class="alert-title">${icon('clock')}<b>添加网盘后，待发文件会继续发送</b></div><p>你选择了仅经网盘，文件会先保留在本机。</p><div class="alert-actions">${htmlButton('add','添加网盘','')}${htmlButton('policy','更改使用方式','')}</div></div>`:'';if(a.status==='connected')return '';const title=a.status==='expired'?'重新登录，就能继续使用网盘':a.status==='full'?'腾出一点空间，继续传文件':'这个网盘已暂停';let description=a.status==='full'?`还剩 ${a.remainingMB??12} MB，放不下待发的 80 MB 文件。`:a.status==='expired'?'登录已过期，已保存的文件不会因此删除。':'已在网盘中的文件会保留。';description+=state.policy==='cloud'?'仅经网盘已开启，待发文件会等你恢复。':'自动模式下，新发送会使用其他可用方式。';const primary=a.status==='expired'?htmlButton('reauth','重新登录','',a.id):a.status==='full'?htmlButton('cleanup-now','查看可清理文件','',a.id):htmlButton('resume','恢复使用','',a.id);return `<div class="alert"><div class="alert-title">${icon(a.status==='paused'?'pause':'warning')}<b>${title}</b></div><p>${description}</p><div class="alert-actions">${primary}${a.status==='full'?htmlButton('default','换一个网盘',''):htmlButton('chat','回到会话','')}</div></div>`}
function render(){persist();$('#nav-chat').innerHTML=icon('chat')+'<span>会话</span>';$('#nav-cloud').innerHTML=icon('cloud')+'<span>我的网盘</span>';$('#device-icon').innerHTML=icon('pc');$('#nav-chat').classList.toggle('active',view==='chat');$('#nav-cloud').classList.toggle('active',view==='cloud');document.querySelectorAll('[data-action=scenario]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.value===state.scenario)));if(view==='chat'){renderChat();return}$('#main').innerHTML=`<header class="page-header"><button class="iconbtn mobile-back" data-action="chat" aria-label="返回会话">${icon('back')}</button><div class="header-title"><h1>我的网盘</h1><p>从这台设备发送时，按需用网盘中转。</p></div><div class="header-buttons"><button class="primary" data-action="add" aria-label="添加网盘">${icon('plus')}<span>添加网盘</span></button></div></header><div class="content">${issueBanner()}<div class="section-head"><h2>已连接的账号</h2><span>${state.accounts.length?'只用于本机发送':'可稍后添加'}</span></div>${state.accounts.length?`<div class="accounts">${state.accounts.map(accountCard).join('')}</div><button class="add-account" data-action="add">${icon('plus')}添加另一个网盘</button>`:`<section class="empty"><div class="empty-illustration">${providerIcon('ali')}${providerIcon('baidu')}</div><h2>把你的网盘接过来</h2><p>选一个常用网盘，登录后就能用于中转。发送时不用再选文件夹。</p>${htmlButton('add','添加网盘')}${htmlButton('chat','先去传文件','textbtn')}</section>`}<div class="optional-note">${icon('info')}<span>不添加网盘，也可以直接传文件。</span>${htmlButton('about','了解更多','textbtn')}</div><div class="section-head"><h2>使用偏好</h2><span>仅在这台设备生效</span></div><section class="settings">${setting('policy','使用方式',state.policy==='auto'?'按可用情况选择传输方式':'网盘不可用时保留待发文件',state.policy==='auto'?'自动':'仅经网盘','route')}${setting('default','默认中转盘','需要网盘时，先用这个账号',defaultAccount()?providers[defaultAccount().provider].name:'尚未选择','cloud')}${setting('cleanup','清理网盘中的中转文件','只处理 MPT 创建的文件',state.cleanup==='manual'?'手动清理':state.cleanup==='7'?'全部接收后 7 天':'全部接收后 30 天','broom')}</section><div class="foot-actions">${htmlButton('privacy',icon('shield')+'账号与设备授权','textbtn')}${htmlButton('help','帮助与诊断 '+icon('chevron'),'textbtn')}</div></div>`;document.documentElement.dataset.screenshotReady='true'}
function add(){modal('添加网盘',`<p>选择你常用的网盘。连接后，MPT 会准备专用文件夹。</p>${Object.entries(providers).map(([id,p])=>`<button class="provider-row" data-action="provider" data-id="${id}">${providerIcon(id)}<span class="grow"><strong>${p.name}</strong><small>登录并确认授权</small></span>${icon('chevron','arrow')}</button>`).join('')}<p class="caption">登录流程为交互演示，尚未接入真实账号。</p>`,htmlButton('close','暂不添加','secondary'))}
function beginAuth(provider,existingId=null){authContext={provider,existingId};const p=providers[provider];modal(existingId?'重新连接'+p.name:'连接'+p.name,`<div class="center">${providerIcon(provider,true)}<h3>${existingId?'继续使用原来的账号':'在网盘页面确认授权'}</h3><p>${existingId?'原有文件夹和使用偏好会保留。':'完成后会自动返回 MPT。'}</p></div><div class="scope-list"><p>${icon('folder')}自动准备 MPT 专用文件夹</p><p>${icon('pc')}用于这台设备发送文件</p><p>${icon('shield')}不会把账号登录信息发给其他设备</p></div><div class="permission-note">请在网盘授权页确认权限范围。MPT 不需要你在这里输入账号密码。</div><p class="caption">演示界面；实际登录方式和权限以该网盘的接入能力为准。</p>`,htmlButton('auth-web',mobile()?'在浏览器继续（演示）':'网页登录（演示）')+(!mobile()?htmlButton('auth-qr','扫码登录（演示）','secondary'):''))}
function authPreview(qr=false){const p=providers[authContext.provider];modal('登录与授权 · 演示',`<p>这是登录后的确认页示意，不会打开真实登录页，也不采集账号信息。</p><div class="auth-preview"><div class="browser-strip">${icon('lock')}网盘登录预览</div><div class="auth-content">${providerIcon(authContext.provider)}<b>${p.name}</b>${qr?'<div class="qr-placeholder" aria-label="不可扫描的二维码示意"><span>示意码</span></div><p>在另一台手机确认登录后，返回 MPT。</p>':'<div class="account-chip">示例账号：小林</div><p>授权应用访问和写入网盘文件。<br>正式授权页会显示实际申请的权限。</p>'}</div></div><div class="mini-links">${qr?htmlButton('auth-web','改用网页登录',''):(!mobile()?htmlButton('auth-qr','改用扫码登录',''):'')}${htmlButton('auth-fail','模拟登录失败','')}</div>`,htmlButton('authorized','演示：同意并返回 MPT')+htmlButton('auth-cancel','暂不授权','secondary'))}
function authFailed(cancel=false){modal(cancel?'暂未连接网盘':'这次没能完成登录',`<div class="center"><div class="success-icon failure-icon">${icon(cancel?'info':'warning')}</div><p>${cancel?'你的网盘账号没有添加到 MPT。':'可以再试一次，也可以稍后再连接。'}</p></div><div class="info-block">${state.policy==='cloud'?'你选择了仅经网盘。待发文件会继续保留，不会改用应用中转。':'你仍然可以返回会话，用已有方式传文件。'}</div>`,htmlButton('auth-retry','重新登录')+htmlButton('chat','先回到会话','secondary'))}
function prepare(){modal('正在准备网盘',`<div class="center">${providerIcon(authContext.provider,true)}<h3>把准备工作交给 MPT</h3><p>不用填写地址，也不用手动创建文件夹。</p></div><div class="progress-steps"><div class="step">${icon('check')}已确认账号</div><div class="step">${icon('folder')}准备 MPT 专用文件夹</div><div class="step pending">${icon('shield')}确认可读写</div></div><p class="caption">准备过程为模拟。</p>`,htmlButton('auth-cancel','暂不连接','secondary'));const ticket=generation;setTimeout(()=>{if(ticket!==generation)return;connected()},900)}
function connected(){const existing=getAccount(authContext.existingId);let a;if(existing){a=existing;a.status='connected'}else{const p=providers[authContext.provider];a={id:authContext.provider+'-'+Date.now(),provider:authContext.provider,nickname:'小林',folder:'MPT',status:'connected',percent:p.percent,used:p.used,space:authContext.provider==='baidu'?'1.75 TB':'896 GB'};state.accounts.push(a);if(!state.defaultId)state.defaultId=a.id}activeAccount=a.id;state.scenario='custom';render();modal('网盘已连接',`<div class="center"><div class="success-icon">${icon('check')}</div><h3>回到会话，就可以发文件了</h3><p>${providers[a.provider].name} · ${esc(a.nickname)}</p></div><div class="plain-list"><div class="list-row">${icon('folder')}<span>中转文件夹</span><small>${esc(a.folder)}</small></div><div class="list-row">${icon('shield')}<span>使用设备</span><small>这台设备</small></div></div>${state.defaultId!==a.id?`<label class="check-row"><input type="checkbox" id="new-default"><span>设为默认中转盘<small>这台设备需要网盘时优先使用它。</small></span></label>`:'<div class="info-block">已设为这台设备的默认中转盘。接收文件的设备不需要登录同一网盘。</div>'}`,htmlButton('connected-chat','回到会话')+htmlButton('connected-manage','查看网盘','secondary'))}
function finishConnect(toChat){if($('#new-default')?.checked)state.defaultId=activeAccount;closeDialog();view=toChat?'chat':'cloud';render()}
function manage(id){const a=getAccount(id);if(!a)return;activeAccount=id;modal('管理'+providers[a.provider].name,`<div class="center">${providerIcon(a.provider,true)}<h3>${esc(a.nickname)}</h3><p>${accountStatus(a)} · 仅这台设备</p></div><div class="plain-list">${`<button class="list-row" data-action="folder" data-id="${id}">${icon('folder')}<span>中转文件夹</span><small>${esc(folderLabel(a))}</small>${icon('chevron','arrow')}</button>`}<button class="list-row" data-action="set-default" data-id="${id}">${icon('cloud')}<span>${state.defaultId===id?'当前默认中转盘':'设为默认中转盘'}</span>${state.defaultId===id?icon('check'):icon('chevron','arrow')}</button><button class="list-row" data-action="cleanup-now" data-id="${id}">${icon('broom')}<span>清理中转文件</span>${icon('chevron','arrow')}</button><button class="list-row" data-action="reauth" data-id="${id}">${icon('refresh')}<span>重新登录</span>${icon('chevron','arrow')}</button></div><div class="info-block">连接信息留在本机。其他设备领取消息中的文件时，不需要拿到你的网盘账号。</div>`,htmlButton(a.status==='paused'?'resume':'pause',a.status==='paused'?'恢复使用':'暂停使用','secondary',id)+htmlButton('disconnect','断开连接','danger',id))}
function folder(id){const a=getAccount(id);if(!a)return;activeAccount=id;browse='';folderView()}
function folderView(){const a=getAccount();const children=browse===''?['MPT','工作资料','我的文档']:browse==='工作资料'?['项目','归档']:[];const target=browse.endsWith('MPT')?browse:[browse,'MPT'].filter(Boolean).join('/');modal('选择保存位置',`<p>选好位置后，MPT 会使用其中的专用文件夹。无需填写路径。</p><div class="folder-browser"><div class="breadcrumbs"><button data-action="folder-root">${providers[a.provider].name}</button>${browse?' / '+esc(browse):''}</div>${children.length?children.map(name=>`<button class="list-row" data-action="folder-enter" data-id="${esc(name)}">${icon('folder')}<span>${name}</span>${icon('chevron','arrow')}</button>`).join(''):'<p class="caption" style="padding:16px;margin:0!important">这个位置里没有其他文件夹。</p>'}</div><div class="folder-selected">将使用：${esc(target)}</div><p class="caption">仅影响以后发送的文件，已有文件不会移动。</p>`,htmlButton('folder-save','使用此位置')+htmlButton('folder-default','保持默认 MPT','secondary'))}
function policy(){modal('使用方式',`<p>设置这台设备发送文件时的选择。</p><label class="option"><input type="radio" name="policy" value="auto" ${state.policy==='auto'?'checked':''}><span><strong>自动</strong><small>优先直连；需要中转时使用默认网盘。网盘不可用时，可以使用应用中转。</small></span></label><label class="option"><input type="radio" name="policy" value="cloud" ${state.policy==='cloud'?'checked':''}><span><strong>仅经网盘</strong><small>只通过默认网盘发送。网盘不可用就等待，不改用应用中转或直连。</small></span></label><div class="info-block">${state.accounts.length?'不会更改其他设备的设置。':'还没有连接网盘。如果选择仅经网盘，文件会先留在待发队列。'}</div>`,htmlButton('policy-save','保存'))}
function chooseDefault(){modal('默认中转盘',`<p>需要网盘中转时，使用你选定的账号。</p>${state.accounts.length?state.accounts.map(a=>`<label class="option"><input type="radio" name="default-account" value="${a.id}" ${state.defaultId===a.id?'checked':''}><span class="grow"><strong>${providers[a.provider].name} · ${esc(a.nickname)}</strong><small>${accountStatus(a)} · ${esc(a.folder)}</small></span></label>`).join(''):'<div class="info-block">还没有连接网盘。添加后会自动设为默认中转盘。</div>'}`,state.accounts.length?htmlButton('default-save','保存'):htmlButton('add','添加网盘'))}
function cleanupPolicy(){modal('清理中转文件',`<p>只清理 MPT 创建的中转副本，不动你的其他网盘文件。</p>${[['manual','手动清理','由你查看并确认清理。'],['30','全部接收后保留 30 天','所有接收方已保存后开始计时。'],['7','全部接收后保留 7 天','适合不需要长时间重复下载的文件。']].map(([value,title,sub])=>`<label class="option"><input type="radio" name="cleanup" value="${value}" ${state.cleanup===value?'checked':''}><span><strong>${title}</strong><small>${sub}</small></span></label>`).join('')}<div class="info-block">清理后，已下载的本地文件不受影响；从消息里重新下载网盘副本将不再可用。尚未全部接收的文件会保留。</div>`,htmlButton('cleanup-save','保存'))}
function cleanupNow(id){
 const a=getAccount(id);if(!a)return;activeAccount=id;
 const files=[{size:48,name:'项目资料.zip',days:36},{size:80,name:'会议录屏.mp4',days:32}].filter(f=>!a.cleanedFiles?.includes(f.size));
 const list=files.map(f=>`<label class="check-file"><input name="cleanup-file" type="checkbox" value="${f.size}" checked><span><b>${f.name}</b><small>${f.size} MB · 已全部接收 · 已保留 ${f.days} 天</small></span></label>`).join('');
 modal('查看可清理文件',`<p>${providers[a.provider].name} / ${esc(a.folder)}<br>${files.length?'以下文件由 MPT 创建，且所有接收方已保存。':'已接收的中转副本已清理。'}</p>${list}<div class="check-file">${icon('clock')}<span><b>旅行照片.zip</b><small>仍有设备未接收，本次保留</small></span></div><p class="caption">示例文件。清理不会删除接收设备上的副本。</p>`,(files.length?htmlButton('cleanup-confirm','清理所选文件','danger'):'')+htmlButton('close',files.length?'取消':'完成','secondary'))
}
function pause(id){activeAccount=id;modal('暂停这个网盘？',`<p>不会退出账号，也不会删除已有文件。</p><div class="info-block">${state.policy==='cloud'?'仅经网盘已开启。新发送会等待，恢复使用后自动继续。':'自动模式下，新发送会使用其他可用方式。'}<br>尚未领取的网盘文件，可能需要恢复后才能继续领取。</div>`,htmlButton('pause-confirm','暂停使用')+htmlButton('close','继续使用','secondary'))}
function disconnect(id){activeAccount=id;modal('断开网盘连接？',`<p>将移除这台设备保存的登录信息。<b>网盘里的文件会保留。</b></p><div class="info-block">${state.policy==='cloud'?'你选择了仅经网盘。断开后待发文件会保留，直到重新连接。':'以后发送会使用其他可用方式。'}<br>已发出但未领取的文件，可能需要这台设备重新连接网盘。${state.defaultId===id&&state.accounts.length>1?'<br>你可以随后选择另一个默认中转盘。':''}</div><label class="check-row"><input type="checkbox" id="disconnect-confirm"><span>我知道这不会删除网盘文件<small>如需撤销网盘侧授权，可在该网盘的账号设置中操作。</small></span></label>`,htmlButton('disconnect-confirm','断开连接','danger')+htmlButton('close','保持连接','secondary'))}
function privacy(){modal('账号与设备授权',`<div class="scope-list"><p>${icon('pc')}网盘登录信息只保存在这台设备</p><p>${icon('file')}接收方只领取消息中的指定文件</p><p>${icon('shield')}添加设备不会共享你的网盘账号</p></div><p>另一台设备想用这个网盘发送时，需要你的单独确认。接收文件不需要再次登录网盘。</p><div class="info-block">这份原型展示账号管理流程；跨设备授权方式会单独确认后接入。</div>`,htmlButton('close','知道了'))}
function about(){modal('网盘怎样参与传输',`<div class="plain-list"><div class="list-row">${icon('chat')}<span>你照常在会话里发送文件</span></div><div class="list-row">${icon('cloud')}<span>需要时，用已连接的网盘中转</span></div><div class="list-row">${icon('check')}<span>接收方直接领取，不用登录你的网盘</span></div></div><div class="info-block">没有添加网盘时，仍可使用直连和应用中转。<br>网盘能分担应用中转服务器的流量；手机上传和下载仍会消耗网络流量。</div><p class="caption">部分网盘的领取链接需要发送设备在线更新。正式发送时会按实际能力显示可领取或等待状态。</p>`,htmlButton('close','知道了'))}
function help(){modal('帮助与诊断',`<div class="plain-list"><button class="list-row" data-action="about">${icon('info')}<span>不添加网盘也能传吗？</span>${icon('chevron','arrow')}</button><button class="list-row" data-action="privacy">${icon('shield')}<span>账号会同步到其他设备吗？</span>${icon('chevron','arrow')}</button><button class="list-row" data-action="check-connection">${icon('refresh')}<span>检查网盘连接</span>${icon('chevron','arrow')}</button><button class="list-row" data-action="diagnostic">${icon('gear')}<span>诊断信息</span>${icon('chevron','arrow')}</button></div>`,htmlButton('close','完成','secondary'))}
function diagnostic(){modal('诊断信息',`<p>排查问题时使用，日常传输无需配置。</p><div class="diagnostic">本机网盘：${state.accounts.length} 个\n当前策略：${state.policy==='auto'?'自动':'仅经网盘'}\n后台组件：OpenList · 按需运行\n连接检查：${defaultAccount()?accountStatus(defaultAccount()):'尚未添加'}\n数据类型：演示状态\n不包含账号凭据或文件路径</div>`,htmlButton('copy-diagnostic','复制诊断摘要')+htmlButton('help','返回','secondary'))}
function renderChat(){const a=usableAccount();$('#main').innerHTML=`<section class="chat-page"><header class="page-header"><div class="chat-header-title"><h1>文件传输助手</h1><p>我的设备 · 共享会话</p></div><button class="iconbtn" data-action="cloud" aria-label="打开我的网盘">${icon('cloud')}</button></header>${state.policy==='cloud'&&!a?'<div class="alert" style="margin:16px 20px 0"><div class="alert-title">'+icon('clock')+'<b>等待网盘恢复，待发内容已保留</b></div><div class="alert-actions">'+htmlButton('cloud','查看网盘','')+'</div></div>':''}<div class="chat-thread"><div class="chat-date">今天</div><div class="chat-intro">会话里照常发，MPT 会按你的设置选择传输方式。</div>${messages.map((m,i)=>`<div class="message"><button class="message-bubble" data-action="message" data-id="${i}">${m.file?`<span class="message-file">${icon('file')}<span>${esc(m.text)}<small>2.4 MB</small></span></span>`:esc(m.text)}</button><span class="message-status">${esc(m.status)}</span></div>`).join('')}</div><div class="chat-composer">${attachment?'<div class="attachment">'+icon('file')+'项目资料.pdf · 2.4 MB<button data-action="remove-attachment" aria-label="移除附件">×</button></div>':''}<div class="composer-line"><button class="iconbtn" data-action="attach" aria-label="添加示例文件">${icon('plus')}</button><input id="composer" placeholder="写点什么…" aria-label="消息内容" value="${esc(chatDraft)}"><button class="primary" data-action="send">发送</button></div><p class="chat-hint">交互演示 · 只使用示例文件，不上传真实内容</p></div></section>`;document.documentElement.dataset.screenshotReady='true'}
function send(){const text=$('#composer').value.trim();if(!text&&!attachment){notify('先写一句话，或添加示例文件');return}const a=usableAccount(),blocked=state.policy==='cloud'&&!a;const batch=[];if(text)batch.push({text,file:false});if(attachment)batch.push({text:'项目资料.pdf',file:true});for(const m of batch){m.status=blocked?'等待网盘恢复 · 已保留':'发送中';m.route=a?'通过'+providers[a.provider].name+'中转':'通过可用传输方式';messages.push(m);if(!blocked)setTimeout(()=>{m.status='已送达（演示）';if(messages.includes(m)&&view==='chat')renderChat()},750)}attachment=false;chatDraft='';renderChat()}
function resumeWaiting(){const a=usableAccount();if(state.policy==='cloud'&&!a)return;for(const m of messages)if(m.status.startsWith('等待')){m.status='已送达（演示）';m.route=a?'通过'+providers[a.provider].name+'中转':'通过可用传输方式'}}
document.addEventListener('click',event=>{const b=event.target.closest('button[data-action]');if(!b)return;const action=b.dataset.action,id=b.dataset.id,value=b.dataset.value;switch(action){
case'viewport':setMode(value);break;
case'scenario':scenario(value);break;
case'reset':scenario('normal');notify('已重置为示例账号');break;
case'close':closeDialog();break;
case'cloud':closeDialog();view='cloud';render();break;
case'chat':closeDialog();view='chat';render();break;
case'add':add();break;
case'provider':beginAuth(id);break;
case'reauth':beginAuth(getAccount(id).provider,id);break;
case'auth-web':authPreview(false);break;
case'auth-qr':authPreview(true);break;
case'auth-fail':authFailed();break;
case'auth-cancel':authFailed(true);break;
case'auth-retry':beginAuth(authContext.provider,authContext.existingId);break;
case'authorized':prepare();break;
case'connected-chat':finishConnect(true);resumeWaiting();render();break;
case'connected-manage':finishConnect(false);resumeWaiting();render();break;
case'manage':manage(id);break;
case'folder':folder(id);break;
case'folder-enter':browse=[browse,id].filter(Boolean).join('/');folderView();break;
case'folder-root':browse='';folderView();break;
case'folder-default':getAccount().folder='MPT';closeDialog();state.scenario='custom';render();notify('将继续使用 MPT 专用文件夹');break;
case'folder-save':getAccount().folder=browse.endsWith('MPT')?browse:[browse,'MPT'].filter(Boolean).join('/');closeDialog();state.scenario='custom';render();notify('保存位置已更新，已有文件不移动');break;
case'policy':policy();break;
case'policy-save':state.policy=$('input[name=policy]:checked').value;state.scenario='custom';closeDialog();resumeWaiting();render();notify(state.policy==='cloud'?'已设为仅经网盘，不会自动改用其他方式':'已设为自动选择');break;
case'default':chooseDefault();break;
case'default-save':state.defaultId=$('input[name=default-account]:checked')?.value||null;closeDialog();state.scenario='custom';resumeWaiting();render();notify('默认中转盘已更新');break;
case'set-default':state.defaultId=id;state.scenario='custom';render();manage(id);notify('已设为默认中转盘');break;
case'cleanup':cleanupPolicy();break;
case'cleanup-save':state.cleanup=$('input[name=cleanup]:checked').value;closeDialog();state.scenario='custom';render();notify('清理偏好已保存');break;
case'cleanup-now':cleanupNow(id);break;
case'cleanup-confirm':{const selected=[...document.querySelectorAll('input[name=cleanup-file]:checked')];if(!selected.length){notify('请选择要清理的中转文件');break}const a=getAccount();a.cleanedFiles=[...(a.cleanedFiles||[]),...selected.map(c=>Number(c.value))];if(a.status==='full'){const total=selected.reduce((n,c)=>n+Number(c.value),0);a.remainingMB=(a.remainingMB??12)+total;Object.assign(a,{status:a.remainingMB>=80?'connected':'full',space:a.remainingMB+' MB',percent:99.98})}closeDialog();state.scenario='custom';resumeWaiting();render();notify('演示：已清理所选中转副本，其他文件保留');break;}
case'pause':pause(id);break;
case'pause-confirm':getAccount().statusBeforePause=getAccount().status;getAccount().status='paused';closeDialog();state.scenario='custom';render();notify('网盘已暂停，已有文件保留');break;
case'resume':getAccount(id).status=getAccount(id).statusBeforePause||'connected';closeDialog();state.scenario='custom';resumeWaiting();render();notify('已恢复使用');break;
case'disconnect':disconnect(id);break;
case'disconnect-confirm':if(!$('#disconnect-confirm').checked){notify('请先确认已有文件会保留');break}state.accounts=state.accounts.filter(a=>a.id!==activeAccount);if(state.defaultId===activeAccount)state.defaultId=null;closeDialog();state.scenario='custom';render();notify('已断开连接，网盘文件未删除');break;
case'privacy':privacy();break;
case'about':about();break;
case'help':help();break;
case'diagnostic':diagnostic();break;
case'copy-diagnostic':{const report=`MPT 网盘交互演示\n账号数：${state.accounts.length}\n使用方式：${state.policy}\n凭据：不包含`;if(navigator.clipboard?.writeText)navigator.clipboard.writeText(report).then(()=>notify('诊断摘要已复制')).catch(()=>notify('浏览器未允许复制，可直接选择上方摘要'));else notify('可直接选择上方摘要复制');break;}
case'check-connection':{const a=defaultAccount();if(a?.status==='expired')beginAuth(a.provider,a.id);else if(a?.status==='full')cleanupNow(a.id);else if(!a)add();else notify(a.status==='paused'?'账号仍然连接，当前已暂停使用':'演示：账号连接正常，可读写 MPT 文件夹');break;}
case'attach':attachment=true;renderChat();notify('示例文件已放入待发区');break;
case'remove-attachment':attachment=false;renderChat();break;
case'send':send();break;
case'message':{const m=messages[Number(id)];modal('传输详情',`<p>${esc(m.text)}</p><div class="plain-list"><div class="list-row"><span>状态</span><small>${esc(m.status)}</small></div><div class="list-row"><span>本次传输</span><small>${m.status.startsWith('等待')?'尚未开始':esc(m.route)}</small></div></div><div class="info-block">接收方领取指定文件，不需要登录发送方的网盘。这里的发送与接收状态均为模拟。</div>`,htmlButton('close','完成'));break;}
}});
document.addEventListener('input',event=>{if(event.target.id==='composer')chatDraft=event.target.value});
$('#dialog').addEventListener('cancel',event=>{event.preventDefault();closeDialog()});
$('#dialog').addEventListener('click',event=>{if(event.target!==$('#dialog'))return;const r=$('#dialog').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeDialog()});
try{state=JSON.parse(localStorage.getItem('mpt-cloud-v4'))}catch{}if(!state||!Array.isArray(state.accounts))state=fresh();
const query=new URLSearchParams(location.search);if(query.get('mode')==='phone')setMode('phone');if(query.has('scenario'))scenario(query.get('scenario'));else render();
if(query.get('page')==='chat'){view='chat';render()}const panel=query.get('panel');if(panel==='providers')add();else if(panel==='policy')policy();else if(panel==='folder')folder(state.defaultId);else if(panel==='login'){beginAuth(query.get('brand')||'ali');authPreview(false)}else if(panel==='cleanup')cleanupNow(state.defaultId);
document.documentElement.dataset.screenshotReady='true';
