const paths={
 home:'M3 11 12 3l9 8M5 10v10h5v-6h4v6h5V10',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',devices:'M3 5h13v10H3zM1 18h11M18 9h5v12h-5z',activity:'M4 4h16v16H4zM8 8h8M8 12h8M8 16h4',send:'m12 3 0 13M7 8l5-5 5 5M5 13v7h14v-7',receive:'M12 3v13m-5-5 5 5 5-5M5 15v6h14v-6',arrow:'M4 12h16m-6-6 6 6-6 6',chevron:'m9 5 7 7-7 7',back:'m15 5-7 7 7 7',close:'m6 6 12 12M6 18 18 6',plus:'M12 4v16M4 12h16',check:'m5 12 4 4L19 6',laptop:'M4 4h16v12H4zM1 19h22l-3 2H4z',desktop:'M3 3h18v13H3zM12 16v5M8 21h8',phone:'M7 2h10v20H7zM10 18h4',cloud:'M7 18a5 5 0 0 1-1-10 7 7 0 0 1 13 1 4.5 4.5 0 0 1-1 9z',bell:'M6 9a6 6 0 0 1 12 0v5l2 3H4l2-3zM9 20h6',terminal:'m5 6 5 6-5 6M13 18h6',focus:'M12 3v3m0 12v3M3 12h3m12 0h3M5.5 5.5l2 2m9 9 2 2m0-13-2 2m-9 9-2 2M9 12a3 3 0 1 0 6 0 3 3 0 0 0-6 0',clipboard:'M9 3h6v4H9zM9 5H5v17h14V5h-4M9 12h6m-6 4h5',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14zm5 12 6 6',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M3 7l3-4 4 2h4l4-2 3 4-2 4v2l2 4-3 4-4-2h-4l-4 2-3-4 2-4v-2z',sun:'M12 3v2m0 14v2M3 12h2m14 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2M8 12a4 4 0 1 0 8 0 4 4 0 0 0-8 0',moon:'M19 15A8 8 0 0 1 9 5a8 8 0 1 0 10 10z',shield:'m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6zM8 12l3 3 5-6',link:'m9 15 6-6M8 9l-3 3a4 4 0 0 0 6 6l3-3M10 9l3-3a4 4 0 0 1 6 6l-3 3',scan:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M6 12h12',image:'M3 3h18v18H3zM3 17l6-6 5 5 3-3 4 4M15 7h1',keyboard:'M2 6h20v13H2zM5 10h1m3 0h1m3 0h1m3 0h1M5 14h1m3 0h9',pulse:'M2 13h4l3-8 5 15 3-7h5',server:'M3 3h18v7H3zM3 14h18v7H3zM7 6h1m-1 11h1M16 6h2m-2 11h2',spark:'m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5z',fan:'M12 12c-8-10 5-13 5-6 0 3-5 6-5 6Zm0 0c13-2 9 11 3 7-3-1-3-7-3-7Zm0 0c-5 12-14 2-7-1 3-1 7 1 7 1Z',code:'m8 5-6 7 6 7M16 5l6 7-6 7',star:'m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',file:'M5 2h9l5 5v15H5zM14 2v6h5M9 13h6m-6 4h6',refresh:'M20 9a8 8 0 0 0-14-4L3 8m0-5v5h5M4 15a8 8 0 0 0 14 4l3-3m0 5v-5h-5',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zm0 4v6h4',power:'M12 2v10M6 5a9 9 0 1 0 12 0',dots:'M5 12h.01M12 12h.01M19 12h.01'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.grid}"/></svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tools=[
{id:'file',name:'文件互传',desc:'把文件送到另一台设备',icon:'send',group:'连接与协作',local:true},
{id:'notifications',name:'远程通知',desc:'重要消息，随身带走',icon:'bell',group:'连接与协作',local:true},
{id:'commands',name:'远程命令',desc:'常用命令，点一下就好',icon:'terminal',group:'连接与协作',local:true},
{id:'paste',name:'图片快传',desc:'上传剪贴板图片，接着粘贴',icon:'image',group:'日常效率',local:false},
{id:'input',name:'输入监测',desc:'查看使用习惯，记得适时休息',icon:'focus',group:'日常效率',local:false},
{id:'screen',name:'屏幕舒适',desc:'让屏幕适合此刻的光线',icon:'sun',group:'日常效率',local:false},
{id:'ime',name:'输入法管理',desc:'每个应用，用对输入法',icon:'keyboard',group:'日常效率',local:false},
{id:'lag',name:'卡顿清理',desc:'处理影响流畅度的问题',icon:'spark',group:'设备维护',local:false},
{id:'nssm',name:'服务管理',desc:'查看和管理 Windows 服务',icon:'server',group:'设备维护',local:false},
{id:'thermo',name:'温度管理',desc:'散热器、露点与温度趋势',icon:'fan',group:'设备维护',local:false},
{id:'adb',name:'ADB 转发',desc:'连接你的开发设备',icon:'code',group:'开发与自动化',local:false},
{id:'doubao',name:'豆包电脑助手',desc:'让电脑帮你完成操作',icon:'spark',group:'开发与自动化',local:false}
];
const files=[{name:'周末出游计划.pdf',size:'2.4 MB',kind:'PDF',cls:''},{name:'山间的早晨.jpg',size:'4.8 MB',kind:'JPG',cls:'photo'},{name:'设计素材.zip',size:'18.6 MB',kind:'ZIP',cls:'zip'}];
const state={page:'home',history:[],offline:false,first:false,selected:[0],target:'MacBook Pro',relay:false,progress:0,filter:'全部',search:'',read:false,favorites:new Set(['file','notifications','commands','input','paste']),connectedCloud:false,activities:[],deviceName:'MacBook Pro',settings:{notify:true,remind:true,quiet:true}};
let transferTimer=null,toastTimer=null,returnFocus=null;
const $=s=>document.querySelector(s);
function illustration(){return `<svg class="device-art" viewBox="0 0 310 128" role="img" aria-label="手机与电脑之间传递文件"><title>你的设备，彼此相连</title><g id="computer"><rect class="hardware" x="31" y="28" width="153" height="89" rx="8"/><rect class="display" x="38" y="35" width="139" height="72" rx="3"/><path d="M95 38h35" stroke="#cad8ec" stroke-width="3" stroke-linecap="round"/><path d="M22 115h172l-10 7H33Z" fill="#d4dbe4"/><path d="M92 115h40" stroke="#b2bdca" stroke-width="2"/></g><g id="mobile"><rect class="hardware" x="217" y="13" width="55" height="106" rx="10"/><rect x="222" y="20" width="45" height="91" rx="6" fill="#dbe9fd"/><circle cx="244.5" cy="24" r="2" fill="#96acca"/><path d="M236 105h17" stroke="#96acca" stroke-width="2" stroke-linecap="round"/></g><g id="file-in-transit"><rect x="134" y="52" width="41" height="47" rx="8" fill="#b9cce944"/><rect x="130" y="46" width="41" height="47" rx="8" fill="#fff"/><path d="M142 59h16m-16 6h16m-16 6h9" stroke="#88ade2" stroke-width="2" stroke-linecap="round"/><path d="M183 70h31m-5-5 5 5-5 5" fill="none" stroke="var(--blue)" stroke-width="2" stroke-linecap="round"/><circle cx="244" cy="65" r="13" class="accent"/><path d="m238 65 4 4 8-8" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></g></svg>`}
function context(key){const data={home:['01 / 常用','打开，就知道做什么。','高频操作在前，完整工具库在后。设备状态只在你需要它时出现。'],tools:['02 / 工具','完整的能力，有序展开。','按用途找工具，收藏常用项。每个工具都说明运行在哪台设备。'],devices:['03 / 设备','先认识设备，再谈连接。','设备有名字、有状态。配对一次，日后从熟悉的设备开始。'],activity:['04 / 动态','做过的事，有迹可循。','文件到了哪里、消息是否读过，都有清楚的结果，也能再次操作。'],send:['文件互传','选好。点一下。送到。','传输细节由系统处理。直连优先；收件设备离线时，用户选择网盘转交。'],offline:['离线场景','暂时不在线，也有下一步。','先保存在已连接的网盘。保留领取入口，清楚区分“已存入”和“已送达”。'],first:['首次使用','从一个小动作开始。','先添加一台设备。授权和进阶设置在需要它们的时候出现。'],detail:['工具详情','能力完整，界面有重点。','一个页面优先解决一件事。桌面专属工具明确显示执行设备与所需权限。']};const d=data[key]||data.detail;$('#context-index').textContent=d[0];$('#context-title').textContent=d[1];$('#context-copy').textContent=d[2]}
function nav(){const tabs=[['home','home','常用'],['tools','grid','工具'],['devices','devices','设备'],['activity','activity','动态']];$('#tabbar').innerHTML=tabs.map(([id,ic,label])=>`<button class="tab-button ${state.page===id?'active':''}" onclick="go('${id}',true)" ${state.page===id?'aria-current="page"':''}>${icon(ic)}<span>${label}</span></button>`).join('')}
function go(page,root=false){closeSheet();if(root)state.history=[];else state.history.push(state.page);state.page=page;render();$('#app-content').scrollTop=0}
function back(){closeSheet();state.page=state.history.pop()||'home';render();$('#app-content').scrollTop=0}
function subnav(label=''){return `<div class="subnav"><button class="back-button" onclick="back()">${icon('back')}返回</button><span class="subnav-label">${label}</span><button class="round-button" aria-label="设置" onclick="go('settings')">${icon('dots')}</button></div>`}
function heading(title,sub=''){return `<h1 class="page-title">${title}</h1>${sub?`<p class="page-subtitle">${sub}</p>`:''}`}
function row(ic,title,desc,action,color='',tail=''){return `<button class="list-row" onclick="${action}"><span class="icon-box ${color}">${icon(ic)}</span><span class="row-copy"><span class="row-title">${title}</span><span class="row-subtitle">${desc}</span></span>${tail||icon('chevron','chevron')}</button>`}
function home(){return `<div class="page-top"><div><div class="micro-label">MY POWER TOOLS</div><div class="hello">早上好，Chris</div></div><button class="avatar" onclick="go('settings')" aria-label="打开设置">C</button></div><h1 class="home-title">你的随身工具箱。</h1><section class="hero-card" aria-label="文件互传"><div class="hero-top"><div><h2>发到另一台设备</h2><p>照片、文件，都可以。</p></div><span class="hero-mark">${icon('send')}</span></div>${illustration()}<button class="primary" onclick="pickFiles()">发送文件 ${icon('arrow')}</button></section><div class="device-strip"><button class="device-chip" onclick="openDevice('MacBook Pro')">${icon('laptop')}<span>MacBook</span><i class="status-dot"></i></button><button class="device-chip" onclick="openDevice('工作电脑')">${icon('desktop')}<span>工作电脑</span><i class="status-dot ${state.offline?'off':''}"></i></button><button class="device-chip" onclick="pairDevice()">${icon('plus')}<span>添加设备</span></button></div><div class="section-heading"><h2>你的常用</h2><button class="text-button" onclick="go('tools',true)">全部工具 ${'↗'}</button></div><div class="tile-grid">${[...state.favorites].filter(id=>id!=='file').map(id=>{const t=tools.find(x=>x.id===id);const labels={notifications:['远程通知',state.read?'消息已读完':'3 条新消息'],commands:['远程命令','运行常用指令'],input:['休息提醒','工作电脑 · 25 分钟后'],paste:['图片快传','工作电脑 · 6 张图片']};const a=labels[id]||[t.name,t.local?t.desc:'工作电脑 · 点击使用'];return [id,t.icon,a[0],a[1]]}).map(([id,ic,name,desc])=>`<button class="tool-tile" onclick="openTool('${id}')">${icon(ic)}${id==='notifications'&&!state.read?'<span class="tile-badge">3</span>':''}<span class="tile-title">${name}</span><span class="tile-desc">${desc}</span></button>`).join('')}</div><div class="section-heading"><h2>最近</h2><button class="text-button" onclick="go('activity',true)">查看全部</button></div><div class="list-card">${row('receive','产品草图.fig','来自 MacBook Pro · 09:32',"receiptDetail()",'purple','<span class="row-meta">已接收</span>')}</div>`}
function library(){return `${heading('工具','每一种本领，都有用武之地。')}<label class="search-box">${icon('search')}<input type="search" aria-label="搜索工具" placeholder="搜索工具或想做的事" value="${esc(state.search)}" oninput="filterTools(this.value)"></label><div class="filters">${['全部','手机可用','电脑工具','已收藏'].map(x=>`<button class="filter ${state.filter===x?'active':''}" onclick="setFilter('${x}')">${x}</button>`).join('')}</div><div id="tool-results">${libraryResults()}</div>`}
function libraryResults(){const matches=tools.filter(t=>(state.filter!=='手机可用'||t.local)&&(state.filter!=='电脑工具'||!t.local)&&(state.filter!=='已收藏'||state.favorites.has(t.id))&&`${t.name} ${t.desc}`.includes(state.search));if(!matches.length)return `<div class="empty-screen">${icon('search')}<h2>换个词试试</h2><p>可以搜索“文件”“通知”或“电脑”。</p><button class="secondary-button" onclick="clearSearch()">查看全部工具</button></div>`;return [...new Set(matches.map(x=>x.group))].map(group=>`<h2 class="category-title">${group}</h2><div class="list-card">${matches.filter(t=>t.group===group).map(t=>`<button class="list-row tool-library-row" onclick="openTool('${t.id}')"><span class="icon-box ${!t.local?'purple':''}">${icon(t.icon)}</span><span class="row-copy"><span class="row-title">${t.name}</span><span class="row-subtitle">${t.desc}</span></span><span class="tool-platform">${t.local?'手机':'电脑'}</span>${icon('chevron','chevron')}</button>`).join('')}</div>`).join('')}
function filterTools(v){state.search=v;$('#tool-results').innerHTML=libraryResults()}function setFilter(v){state.filter=v;render()}function clearSearch(){state.search='';state.filter='全部';render()}
function deviceCard(name,type,desc,isOnline){return `<button class="device-card" onclick="openDevice('${name}')"><div class="device-card-top"><div class="large-device">${icon(type)}</div><span class="pill ${isOnline?'':'offline'}"><i class="status-dot ${isOnline?'':'off'}"></i>${isOnline?'在线':'离线'}</span></div><h2 class="device-name">${name}</h2><p class="device-description">${desc}</p><div class="device-card-bottom"><span>${isOnline?'可以传文件、运行工具':'上次在线 · 今天 08:40'}</span>${icon('chevron','chevron')}</div></button>`}
function devices(){return `${heading('你的设备','各有所长，彼此相连。')}${deviceCard('MacBook Pro','laptop','macOS · Chris 的笔记本',true)}${deviceCard('工作电脑','desktop','Windows · 书房',!state.offline)}<button class="add-device" onclick="pairDevice()">${icon('plus')}添加一台设备</button><div class="section-heading"><h2>网盘中转</h2></div><div class="list-card">${row('cloud',state.connectedCloud?'我的网盘':'连接一个网盘',state.connectedCloud?'已连接 · 设备离线时也能转交':'给不在线的设备，留一份文件',"setupCloud()")}</div><p class="note">配对后的设备会被记住。你可以随时在设备详情中解除连接。</p>`}
function activity(){return `${heading('动态','每件小事，都有着落。')}<div class="category-title">今天</div><div class="list-card">${state.activities.map((a,i)=>row(a.relay?'cloud':'send',esc(a.name),`${a.relay?'已存入网盘，等待领取':'已发送到 '+esc(a.target)} · 刚刚`,`activityReceipt(${i})`,'green')).join('')}${row('receive','产品草图.fig','来自 MacBook Pro · 09:32',"receiptDetail()",'purple')}${row('terminal','服务器状态','运行完成 · 09:18',"openTool('commands')",'', '<span class="row-meta">查看结果</span>')}${row('bell','构建已完成','工作电脑 · 09:12',"openTool('notifications')",'green')}</div><div class="category-title">昨天</div><div class="list-card">${row('send','会议记录.pdf','已发送到工作电脑 · 18:24',"receiptDetail('会议记录.pdf')")}</div>`}
function notifications(){return `${subnav('远程通知')}${heading('值得你看一眼。',state.read?'所有消息都已读完。':'来自设备的 3 条新消息。')}<div class="section-heading"><h2>今天</h2><button class="text-button" onclick="state.read=true;render();toast('已全部标为已读')">全部已读</button></div><div class="list-card">${[['构建已完成','工作电脑 · 09:12','MyPowerTools 的新版本已构建完成。'],['文件已收到','MacBook Pro · 08:55','会议记录.pdf 已保存到下载文件夹。'],['备份已完成','家用服务器 · 08:30','今天的自动备份已完成。']].map(([t,d,b])=>`<button class="list-row" onclick="readNotification('${t}','${d}','${b}')"><span class="icon-box">${icon('bell')}</span><span class="row-copy"><span class="row-title">${t}</span><span class="row-subtitle">${d}</span></span>${state.read?'':'<i class="notification-unread"></i>'}</button>`).join('')}</div><div class="notice">只提醒你关心的事。可以在通知设置中选择来源与安静时段。</div><button class="quiet-button bottom-space" onclick="go('settings')">通知设置</button>`}
function commands(){return `${subnav('远程命令')}${heading('指令，触手可及。','家用服务器 · 已连接')}<div class="section-heading"><h2>常用指令</h2><button class="text-button" onclick="addCommand()">添加</button></div><div class="list-card">${row('pulse','查看服务器状态','uptime · 只读',"runCommand('查看服务器状态')")}${row('server','查看磁盘空间','df -h · 只读',"runCommand('查看磁盘空间')")}${row('activity','查看服务日志','journalctl · 只读',"runCommand('查看服务日志')")}</div><div class="section-heading"><h2>上次结果</h2><span class="row-meta">09:18</span></div><div class="command-output">$ uptime\n09:18 up 12 days, 4:32\nload average: 0.21, 0.18, 0.15\n\n<span style="color:#8ed4b1">✓ 运行完成</span></div><button class="quiet-button bottom-space" onclick="serverSettings()">管理服务器连接</button>`}
function settings(){return `${subnav('设置')}${heading('按你的习惯。')}<div class="section-heading"><h2>我的手机</h2></div><div class="list-card">${row('phone','Chris 的手机','Android · 当前设备',"renamePhone()")}</div><div class="section-heading"><h2>偏好</h2></div><div class="list-card">${setting('notify','接收设备通知','重要消息及时到达')}${setting('quiet','安静时段','每天 23:00 — 08:00')}<button class="list-row" onclick="toggleTheme()"><span class="row-copy"><span class="row-title">外观</span><span class="row-subtitle">${document.documentElement.dataset.theme==='dark'?'深色':'浅色'}</span></span>${icon('sun')}</button></div><div class="section-heading"><h2>连接与安全</h2></div><div class="list-card">${row('shield','设备权限','查看已允许的设备与操作',"permissions()")}${row('cloud','网盘中转',state.connectedCloud?'已连接':'还未设置',"setupCloud()")}</div><p class="note" style="text-align:center;margin-top:26px">My Power Tools<br>你的工具，按你的方式。</p>`}
function setting(key,name,desc){return `<div class="setting-row"><span class="row-copy"><span class="row-title">${name}</span><span class="row-subtitle">${desc}</span></span><button class="switch" role="switch" aria-label="${name}" aria-checked="${state.settings[key]}" onclick="toggleSetting('${key}',this)"></button></div>`}function toggleSetting(key,el){state.settings[key]=!state.settings[key];el.setAttribute('aria-checked',String(state.settings[key]));toast(`${state.settings[key]?'已开启':'已关闭'}${el.getAttribute('aria-label')}`)}
function openTool(id){if(id==='file'){pickFiles();return}if(id==='notifications'||id==='commands'){go(id);return}go('tool:'+id)}
function toolDetail(id){const t=tools.find(x=>x.id===id);const isFav=state.favorites.has(id);let details='';if(id==='input')details=`<div class="detail-grid"><div class="detail-stat"><span class="row-subtitle">下次休息</span><div class="detail-value">25<small>分钟后</small></div></div><div class="detail-stat"><span class="row-subtitle">今天已休息</span><div class="detail-value">3<small>次</small></div></div></div><div class="list-card bottom-space"><button class="list-row" onclick="usageDetails()"><span class="icon-box">${icon('pulse')}</span><span class="row-copy"><span class="row-title">今天使用电脑 2 小时 18 分</span><span class="row-subtitle">查看键鼠与应用活动</span></span>${icon('chevron','chevron')}</button></div><div class="section-heading"><h2>提醒方式</h2></div><div class="list-card">${setting('remind','开启休息提醒','每 50 分钟，休息 5 分钟')}${row('moon','温和的全屏提醒','沿用电脑上已设置的深色样式',"reminderSettings()")}</div><button class="primary bottom-space" onclick="desktopAction('开始休息','向工作电脑发送开始休息指令，电脑会出现休息提醒。')">现在休息一下</button>`;
else if(id==='paste')details=`<div class="section-heading"><h2>最近的图片</h2></div><div class="list-card">${row('image','界面草图.png','今天 09:20 · 1.2 MB',"imagePreview('界面草图.png')",'purple')}${row('image','灵感参考.jpg','今天 08:45 · 4.8 MB',"imagePreview('灵感参考.jpg')",'green')}</div><p class="note">查看电脑上传过的图片，复用远端路径，也可以取回手机。</p>`;
else if(id==='process')details=`<div class="detail-grid"><div class="detail-stat"><span class="row-subtitle">处理器</span><div class="detail-value">12<small>%</small></div></div><div class="detail-stat"><span class="row-subtitle">内存</span><div class="detail-value">8.2<small>GB</small></div></div></div><div class="section-heading"><h2>当前进程</h2></div><div class="list-card">${row('grid','MyPowerTools','正常运行 · 186 MB',"toast('MyPowerTools：运行正常')")}${row('code','Code','正常运行 · 412 MB',"toast('Code：运行正常')")}</div><button class="secondary-button bottom-space" onclick="toast('状态已刷新 · 示例数据')">刷新状态</button>`;
else if(id==='nssm')details=`<div class="section-heading"><h2>服务</h2></div><div class="list-card">${row('server','文件接收服务','运行中 · 自动启动',"serviceDetail()",'green')}${row('server','备份服务','运行中 · 自动启动',"serviceDetail('备份服务')",'green')}</div>`;
else{const configs={screen:['长读柔光','ScreenEase · 亮度 85% · 5000K','调整显示偏好'],ime:['默认输入法','按应用记住输入习惯','管理应用规则'],lag:['电脑运行顺畅','上次检查 · 今天 09:00','检查卡顿原因'],thermo:['露点保护已开启','SmartBird · 当前温度 24°C','查看温度与控制'],adb:['1 台开发设备','Pixel · 已连接','查看转发规则'],doubao:['等待你的任务','在工作电脑上执行','新建电脑任务']};const c=configs[id];details=`<div class="list-card bottom-space">${row(t.icon,c[0],c[1],`configureTool('${id}')`)}</div><button class="primary bottom-space" onclick="configureTool('${id}')">${c[2]}</button>`}
return `${subnav('电脑工具')}<div class="tool-feature"><span class="icon-box purple">${icon(t.icon)}</span><h1>${t.name}</h1><p>${t.desc}</p></div><button class="list-row" style="padding:0 1px;min-height:44px" onclick="openDevice('工作电脑')">${icon('desktop')}<span class="row-copy"><span class="row-subtitle">运行于工作电脑</span></span><span class="pill ${state.offline?'offline':''}">${state.offline?'离线':'在线'}</span></button>${state.offline?'<div class="notice warning">工作电脑暂时离线。连接恢复后，才能运行此工具。</div>':''}${details}<button class="quiet-button bottom-space favorite" onclick="favorite('${id}')">${isFav?'★ 已加入常用 · 点击移除':'☆ 加入常用'}</button>`}
function render(){let html;if(state.first&&state.page==='home')html=onboarding();else if(state.page.startsWith('tool:'))html=toolDetail(state.page.split(':')[1]);else if(state.page==='device-detail')html=deviceDetail();else html=({home,tools:library,devices,activity,notifications,commands,settings}[state.page]||home)();$('#app-content').innerHTML=`<div class="app-page">${html}</div>`;nav();context(state.first&&state.page==='home'?'first':state.page.startsWith('tool:')?'detail':state.page);document.body.dataset.screenshotReady='true'}
function favorite(id){if(state.favorites.has(id))state.favorites.delete(id);else state.favorites.add(id);render();toast(state.favorites.has(id)?'已加入常用':'已从常用移除')}
function showSheet(content,label='操作'){if(!$('#overlay-root').children.length)returnFocus=document.activeElement;$('#app-content').inert=true;$('#tabbar').inert=true;$('#overlay-root').innerHTML=`<div class="overlay" onclick="if(event.target===this)closeSheet()"><section class="sheet" role="dialog" aria-modal="true" aria-label="${label}"><div class="grabber"></div>${content}</section></div>`;requestAnimationFrame(()=>{const f=$('.sheet button:not(:disabled),.sheet input');if(f)f.focus({preventScroll:true})})}
function closeSheet(){if(transferTimer){clearInterval(transferTimer);transferTimer=null}$('#overlay-root').innerHTML='';$('#app-content').inert=false;$('#tabbar').inert=false;if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});returnFocus=null}
function sheetHeading(title,desc=''){return `<div class="sheet-heading"><div><h2>${title}</h2>${desc?`<p>${desc}</p>`:''}</div><button class="close-button" onclick="closeSheet()" aria-label="关闭">${icon('close')}</button></div>`}
function pickFiles(){context('send');showSheet(`${sheetHeading('想发什么？','选择最近的文件。')}<div class="category-title" style="margin-top:0">最近文件</div>${files.map((f,i)=>`<label class="file-choice"><span class="file-thumb ${f.cls}">${f.kind}</span><span class="row-copy"><span class="row-title">${f.name}</span><span class="row-subtitle">${f.size}</span></span><input type="checkbox" aria-label="选择${f.name}" ${state.selected.includes(i)?'checked':''} onchange="selectFile(${i},this.checked)"></label>`).join('')}<button id="choose-target" class="primary" onclick="chooseTarget()" ${!state.selected.length?'disabled':''}>选择接收设备${state.selected.length?' · '+state.selected.length+' 个文件':''} ${icon('arrow')}</button><p class="note" style="text-align:center;margin-bottom:0">也可以从相册或文件应用分享至 MPT。</p>`,'选择文件')}
function selectFile(i,checked){state.selected=checked?[...new Set([...state.selected,i])]:state.selected.filter(x=>x!==i);const b=$('#choose-target');b.disabled=!state.selected.length;b.innerHTML=`选择接收设备${state.selected.length?' · '+state.selected.length+' 个文件':''} ${icon('arrow')}`}
function fileLabel(){return state.selected.length===1?files[state.selected[0]].name:`${state.selected.length} 个文件`}
function fileSize(){return state.selected.reduce((n,i)=>n+parseFloat(files[i].size),0).toFixed(1)+' MB'}
function fileSummary(){return `<div class="file-summary"><span class="file-thumb">${state.selected.length===1?files[state.selected[0]].kind:'FILES'}</span><span class="row-copy"><span class="row-title">${fileLabel()}</span><span class="row-subtitle">${fileSize()} · 已准备好</span></span><button class="text-button" onclick="pickFiles()">更改</button></div>`}
function chooseTarget(){if(!state.selected.length)return;showSheet(`${sheetHeading('发给哪台设备？','点一下设备，即可发送。')}${fileSummary()}<button class="target-row" onclick="startTransfer('MacBook Pro',false)"><span class="icon-box">${icon('laptop')}</span><span class="row-copy"><span class="row-title">MacBook Pro</span><span class="row-subtitle">Chris 的笔记本</span></span><span class="target-badge">在线</span>${icon('chevron','chevron')}</button><button class="target-row" onclick="${state.offline?'offerRelay()':"startTransfer('工作电脑',false)"}"><span class="icon-box">${icon('desktop')}</span><span class="row-copy"><span class="row-title">工作电脑</span><span class="row-subtitle">${state.offline?'暂时离线 · 可通过网盘转交':'Windows · 书房'}</span></span><span class="target-badge ${state.offline?'off':''}">${state.offline?'离线':'在线'}</span>${icon('chevron','chevron')}</button><button class="quiet-button bottom-space" onclick="pairDevice()">${'+ 添加另一台设备'}</button><p class="note" style="text-align:center">优先直接传输，文件只发送给你已配对的设备。</p>`,'选择接收设备')}
function offerRelay(){context('offline');showSheet(`${sheetHeading('电脑不在线，也没关系。','可以先把文件放进你的网盘。')}${fileSummary()}<div class="list-card">${row('cloud',state.connectedCloud?'我的网盘 · 已连接':'设置网盘中转',state.connectedCloud?'工作电脑上线后可领取':'首次使用，先连接一个网盘',"setupCloud(true)")}</div><div class="notice">文件存入网盘后会显示“等待领取”。接收设备确认收到后，才会显示“已送达”。</div><button class="primary bottom-space" onclick="${state.connectedCloud?"startTransfer('工作电脑',true)":"setupCloud(true)"}">${state.connectedCloud?'存入网盘，稍后领取':'连接网盘并继续'}</button><button class="quiet-button" onclick="chooseTarget()">换一台设备</button>`,'离线转交')}
function startTransfer(target,relay){state.target=target;state.relay=relay;state.progress=0;showSheet(`${sheetHeading(relay?'正在存入网盘':'正在发送')}<div class="transfer-display"><div class="large-device">${icon(relay?'cloud':target==='MacBook Pro'?'laptop':'desktop')}</div><h3>${relay?'稍后转交给工作电脑':target}</h3><p class="page-subtitle">${fileLabel()}</p></div><div class="progress-track" role="progressbar" aria-label="传输进度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-fill" id="progress-fill"></div></div><div class="progress-meta"><span id="progress-label">正在准备</span><span>${fileSize()}</span></div><button class="quiet-button bottom-space" onclick="cancelTransfer()">取消传输</button>`,'传输进度');transferTimer=setInterval(()=>{state.progress=Math.min(state.progress+17,100);$('#progress-fill').style.width=state.progress+'%';$('.progress-track').setAttribute('aria-valuenow',state.progress);$('#progress-label').textContent=state.progress+'%';if(state.progress===100){clearInterval(transferTimer);transferTimer=null;state.activities.unshift({name:fileLabel(),size:fileSize(),target,relay});transferSuccess()}},260)}
function cancelTransfer(){closeSheet();toast('传输已取消，可重新选择设备')}
function transferSuccess(){const relay=state.relay;showSheet(`<div class="success-view"><div class="success-icon">${icon(relay?'cloud':'check')}</div><h2>${relay?'已存好，等它上线。':'送到了。'}</h2><p>${relay?'文件已存入你的网盘。<br>工作电脑上线后，可从 MPT 领取。':`文件已送到 ${state.target}。<br>现在就可以在电脑上使用。`}</p><div class="receipt"><div class="receipt-row"><span>文件</span><strong>${fileLabel()}</strong></div><div class="receipt-row"><span>大小</span><strong>${fileSize()}</strong></div><div class="receipt-row"><span>${relay?'状态':'保存到'}</span><strong>${relay?'等待工作电脑领取':'下载 / MPT'}</strong></div><div class="receipt-row"><span>传输方式</span><strong>${relay?'网盘中转':'设备直连'}</strong></div></div><button class="primary" onclick="closeSheet();go('activity',true)">完成</button>${relay?'<button class="quiet-button" onclick="toast(\'示例领取码：MPT-8421\')">查看领取信息</button>':'<button class="quiet-button" onclick="pickFiles()">再发一份</button>'}</div>`,'传输结果')}
function receiptDetail(name='产品草图.fig'){showSheet(`${sheetHeading('文件已接收')}<div class="file-summary"><span class="icon-box purple">${icon('file')}</span><span class="row-copy"><span class="row-title">${esc(name)}</span><span class="row-subtitle">8.6 MB · 来自 MacBook Pro</span></span></div><div class="receipt"><div class="receipt-row"><span>保存位置</span><strong>下载 / MPT</strong></div><div class="receipt-row"><span>接收时间</span><strong>今天 09:32</strong></div></div><button class="primary" onclick="toast('原型演示：在实际产品中打开系统文件查看器')">打开文件</button><button class="quiet-button" onclick="pickFiles()">发送到另一台设备</button>`,'文件详情')}
function activityReceipt(i){const a=state.activities[i];showSheet(`${sheetHeading(a.relay?'等待领取':'已送达')}<div class="receipt"><div class="receipt-row"><span>文件</span><strong>${esc(a.name)}</strong></div><div class="receipt-row"><span>接收设备</span><strong>${a.target}</strong></div><div class="receipt-row"><span>状态</span><strong>${a.relay?'已存入网盘 · 等待领取':'已收到'}</strong></div></div><button class="primary" onclick="closeSheet()">知道了</button>`,'发送记录')}
function setupCloud(resume=false){showSheet(`${sheetHeading(state.connectedCloud?'网盘已连接':'让离线的设备，也能收到。',state.connectedCloud?'你可以随时管理中转设置。':'连接一次，以后随手转交。')}${state.connectedCloud?`<div class="list-card">${row('cloud','我的网盘','MacBook Pro · 中转服务在线',"toast('当前中转目录：MPT / 文件中转')")}</div><button class="primary bottom-space" onclick="${resume?"offerRelay()":"closeSheet()"}">${resume?'继续发送':'完成'}</button>`:`<div class="list-card">${['阿里云盘','百度网盘','已有网盘服务'].map(name=>row('cloud',name,name==='已有网盘服务'?'连接现有 OpenList / WebDAV':'通过网盘账号授权',`authorizeCloud('${name}',${resume})`)).join('')}</div><p class="note">选择一台常在线电脑作为中转端。本例使用 MacBook Pro，由 MPT 集成 OpenList 管理网盘连接。</p><p class="note">这是拟议配置流程。网盘授权与后台运行仍需正式实现。</p>`}`,'网盘中转')}
function authorizeCloud(name,resume){showSheet(`${sheetHeading('连接'+name,'在实际产品中打开账号授权页面。')}<div class="empty-screen" style="padding:5px 0 12px">${icon('cloud')}<p>中转由 MacBook Pro 提供，使用时需保持在线。<br>此处演示授权完成后的体验。</p></div><button class="primary" onclick="state.connectedCloud=true;${resume?'offerRelay()':"closeSheet();go('devices',true)"};toast('示例网盘已连接')">模拟授权完成</button><button class="quiet-button" onclick="setupCloud(${resume})">返回选择</button>`,'授权流程演示')}
function onboarding(){return `<div class="page-top"><div class="micro-label">MY POWER TOOLS</div><button class="text-button" onclick="state.first=false;render()">先逛逛</button></div><div class="onboarding-art">${illustration()}</div><h1 class="onboarding-title">你的设备。<br>一起，更好用。</h1><p class="onboarding-desc">传一份文件，接一条消息，<br>让电脑帮你做一件事。</p><div class="onboarding-point">${icon('link')}<span>连一次，以后都记得<small>用连接码找到你的另一台设备</small></span></div><div class="onboarding-point">${icon('shield')}<span>每份权限，都由你决定<small>只允许你需要的操作</small></span></div><button class="primary bottom-space" onclick="pairDevice()">连接第一台设备 ${icon('arrow')}</button><button class="quiet-button" onclick="state.first=false;go('tools',true)">先看看能做什么</button>`}
function pairDevice(){showSheet(`${sheetHeading('认识你的另一台设备。','在电脑上打开 MPT，选择“添加设备”。')}<div class="notice">输入电脑显示的 6 位连接码，开始配对。</div><form onsubmit="event.preventDefault();confirmPair()"><label class="field-label" for="pair-code">连接码</label><input class="field" id="pair-code" inputmode="numeric" maxlength="6" pattern="[0-9]{6}" placeholder="例如 842916" required autocomplete="off"><p class="note">演示连接码：842916。实际配对需要双方确认。</p><button class="primary" type="submit">连接设备</button></form><button class="quiet-button" onclick="scanDemo()">${'使用扫码连接'}</button>`,'添加设备')}
function scanDemo(){showSheet(`${sheetHeading('扫描电脑上的连接码')}<div class="empty-screen" style="padding:10px">${icon('scan')}<p>实际产品会在此请求相机权限，<br>扫描电脑端 MPT 显示的二维码。</p></div><button class="primary" onclick="confirmPair(true)">模拟识别成功</button><button class="quiet-button" onclick="pairDevice()">改用连接码</button>`,'扫码连接示意')}
function confirmPair(simulated=false){if(!simulated&&$('#pair-code').value!=='842916'){toast('连接码不匹配，请输入示例码 842916');return}showSheet(`${sheetHeading('是这台电脑吗？','请在电脑上确认本次连接。')}<div class="file-summary"><span class="icon-box">${icon('laptop')}</span><span class="row-copy"><span class="row-title">MacBook Pro</span><span class="row-subtitle">Chris 的笔记本</span></span></div><div class="notice">本次只允许文件互传。通知接收和远程操作会在首次使用时单独请求。</div><button class="primary bottom-space" onclick="state.first=false;closeSheet();go('devices',true);toast('已配对 MacBook Pro · 示例')">模拟电脑确认</button><button class="quiet-button" onclick="pairDevice()">不是这台，返回</button>`,'确认配对设备')}
function openDevice(name){state.deviceName=name;go('device-detail')}
function deviceDetail(){const name=state.deviceName,win=name==='工作电脑',offline=win&&state.offline;return `${subnav('设备详情')}<div class="tool-feature"><div class="large-device">${icon(win?'desktop':'laptop')}</div><h1 style="margin-top:15px">${name}</h1><p>${win?'Windows · 书房':'macOS · Chris 的笔记本'}<br>${offline?'上次在线 · 今天 08:40':'已连接，可随时传文件'}</p></div><button class="primary" onclick="${offline?'offerRelay()':'pickFiles()'}">${offline?'通过网盘转交':'发送文件'} ${icon('send')}</button><div class="section-heading"><h2>在这台设备上</h2></div><div class="list-card">${row('bell','远程通知','查看这台设备的消息',"openTool('notifications')")}${row('terminal','远程命令','使用已授权的常用命令',"openTool('commands')")}${win?row('focus','休息提醒','25 分钟后，休息一下',"openTool('input')")+row('sun','屏幕舒适','查看当前显示方案',"openTool('screen')"):''}</div><div class="section-heading"><h2>设备设置</h2></div><div class="list-card">${row('shield','允许的操作','文件互传 · 通知',"permissions()")}</div><button class="quiet-button bottom-space" onclick="unpair()">解除连接</button>`}
function unpair(){showSheet(`${sheetHeading('解除与 '+state.deviceName+' 的连接？','下次使用时需要重新配对。')}<button class="primary" onclick="closeSheet();toast('原型已演示解除流程，示例设备保留')">解除连接</button><button class="quiet-button" onclick="closeSheet()">保留连接</button>`,'解除设备连接')}
function readNotification(t,d,b){state.read=true;showSheet(`${sheetHeading(t,d)}<p class="notification-body">${b}</p><button class="primary bottom-space" onclick="closeSheet();render()">标为已读</button>`,'消息详情')}
function runCommand(name){showSheet(`${sheetHeading(name,'家用服务器 · 只读命令')}<div class="command-output">${name==='查看服务器状态'?'$ uptime\n09:41 up 12 days, 4:55\nload average: 0.21, 0.18, 0.15':name==='查看磁盘空间'?'$ df -h\nFilesystem   Size  Used  Avail\n/dev/sda1    256G  108G  148G':'$ journalctl --lines=3\n09:40:02  Service ready\n09:40:12  Received request\n09:40:12  Completed'}\n\n<span style="color:#8ed4b1">✓ 运行完成 · 示例结果</span></div><button class="primary bottom-space" onclick="closeSheet()">完成</button>`,'命令运行结果')}
function addCommand(){showSheet(`${sheetHeading('把常用指令放到手边。')}<form onsubmit="event.preventDefault();closeSheet();toast('示例指令已保存')"><label class="field-label" for="cmd-name">名称</label><input class="field" id="cmd-name" required placeholder="例如：查看磁盘空间"><label class="field-label" for="cmd-content">命令</label><input class="field" id="cmd-content" required placeholder="df -h"><p class="note">新命令在首次执行时确认权限。此原型不会连接或执行。</p><button class="primary bottom-space" type="submit">保存指令</button></form>`,'添加远程命令')}
function serverSettings(){showSheet(`${sheetHeading('家用服务器','SSH 连接')}<div class="list-card">${row('server','已保存的连接','主机地址和密钥只在此处管理',"toast('连接信息仅为原型示例')")}</div><p class="note">日常使用常用指令。需要更换服务器或密钥时，再打开连接设置。</p><button class="primary" onclick="closeSheet()">完成</button>`,'服务器设置')}
function permissions(){showSheet(`${sheetHeading('允许哪些操作？','随时可改，不影响其他设备。')}<div class="list-card">${setting('transferPermission','接收文件','接收前保留系统文件权限检查')}${setting('notify','接收通知','接收已授权来源的消息')}${setting('controlPermission','电脑工具控制','首次运行敏感操作时再次确认')}</div><button class="primary bottom-space" onclick="closeSheet();toast('权限偏好已保存 · 示例')">完成</button>`,'设备权限')}
function reminderSettings(){showSheet(`${sheetHeading('按自己的节奏休息。')}<label class="field-label" for="reminder-interval">连续使用多久后提醒</label><select id="reminder-interval" class="field"><option>25 分钟</option><option selected>50 分钟</option><option>60 分钟</option></select><label class="field-label" for="rest-time">每次休息</label><select id="rest-time" class="field"><option>3 分钟</option><option selected>5 分钟</option><option>10 分钟</option></select><div class="notice">电脑继续使用已设置的深色提醒界面。手机负责调整偏好。</div><button class="primary bottom-space" onclick="desktopAction('保存提醒设置','将当前间隔同步到工作电脑。')">保存到工作电脑</button>`,'休息提醒设置')}
function desktopAction(title,desc){if(state.offline){showSheet(`${sheetHeading('工作电脑暂时离线。','连接恢复后，再继续这个操作。')}<button class="primary" onclick="closeSheet()">知道了</button>`,'设备离线');return}showSheet(`${sheetHeading(title,desc)}<div class="notice">拟议的远程操作会沿用 MPT 的权限确认；需要管理员权限时由电脑端处理。</div><button class="primary bottom-space" onclick="closeSheet();toast('已演示操作确认，不会控制真实电脑')">确认 · 原型演示</button><button class="quiet-button" onclick="closeSheet()">取消</button>`,'确认电脑操作')}
function imagePreview(name){showSheet(`${sheetHeading(name,'工作电脑 · 图片历史')}<div style="height:180px;background:var(--app);border-radius:16px;display:grid;place-items:center"><div style="width:150px;height:110px;border:1px solid var(--line);border-radius:14px;padding:17px;background:var(--card)"><div style="width:50%;height:8px;background:var(--soft);border-radius:5px"></div><div style="height:38px;background:var(--soft);border-radius:7px;margin:13px 0"></div><div style="height:7px;width:70%;background:var(--divider);border-radius:5px"></div></div></div><button class="primary bottom-space" onclick="toast('示例远端路径：uploads/image.png')">复制远端路径</button><button class="quiet-button" onclick="closeSheet();toast('已演示取回图片，原型不实际下载')">保存到手机</button>`,'图片预览')}
function serviceDetail(name='文件接收服务'){showSheet(`${sheetHeading(name,'工作电脑 · 正在运行')}<div class="receipt"><div class="receipt-row"><span>启动方式</span><strong>自动</strong></div><div class="receipt-row"><span>运行状态</span><strong>正常</strong></div></div><button class="secondary-button" onclick="desktopAction('重启${name}','服务会短暂中断，请确认当前没有任务。')">重启服务</button><button class="quiet-button" onclick="closeSheet()">返回</button>`,'服务详情')}
function configureTool(id){const t=tools.find(x=>x.id===id);const options={screen:['长读柔光','专注办公','自定义亮度与色温'],ime:['跟随应用','始终中文','始终英文'],lag:['检查高占用进程','查看后台服务','查看启动项目'],thermo:['温度曲线','散热器控制','露点保护设置'],adb:['查看设备','管理转发端口','连接新设备'],doubao:['打开应用','整理文件','自定义任务']};showSheet(`${sheetHeading(t.name,'工作电脑 · 选择需要的操作')}<div class="list-card">${options[id].map(x=>row(t.icon,x,'点击查看执行确认',`desktopAction('${x}','此操作将在工作电脑上执行。')`)).join('')}</div><button class="quiet-button bottom-space" onclick="closeSheet()">返回</button>`,'工具操作')}
function renamePhone(){showSheet(`${sheetHeading('给手机起个名字。')}<form onsubmit="event.preventDefault();closeSheet();toast('设备名称已保存 · 示例')"><label class="field-label" for="phone-name">设备名称</label><input class="field" id="phone-name" value="Chris 的手机" required><button class="primary bottom-space" type="submit">保存</button></form>`,'修改设备名称')}
function toast(msg){clearTimeout(toastTimer);$('#toast').textContent=msg;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600)}
function toggleTheme(){const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';$('.theme-button').innerHTML=icon(dark?'sun':'moon');if(state.page==='settings')render();try{localStorage.setItem('mpt-concept-theme',dark?'dark':'light')}catch{}}
function scenario(name){closeSheet();state.first=name==='first';state.offline=name==='offline';state.page='home';state.history=[];state.selected=[0];render();document.querySelectorAll('.scene-button').forEach(b=>b.classList.toggle('selected',b.dataset.scene===name));if(name==='send')pickFiles();if(name==='offline'){context('offline');chooseTarget()}if(name==='first')context('first')}
function resetDemo(){state.activities=[];state.connectedCloud=false;state.read=false;state.search='';state.filter='全部';state.settings={notify:true,remind:true,quiet:true,transferPermission:true,controlPermission:false};state.favorites=new Set(['file','notifications','commands','input','paste']);scenario('daily')}
state.settings.transferPermission=true;state.settings.controlPermission=false;
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('.sheet')){closeSheet();return}if(e.key==='Tab'&&$('.sheet')){const all=[...$('.sheet').querySelectorAll('button:not(:disabled),input,select,[tabindex="0"]')];if(!all.length)return;const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}});
try{document.documentElement.dataset.theme=localStorage.getItem('mpt-concept-theme')||'light'}catch{}$('.theme-button').innerHTML=icon(document.documentElement.dataset.theme==='dark'?'sun':'moon');
const query=new URLSearchParams(location.search);if(query.get('theme'))document.documentElement.dataset.theme=query.get('theme');scenario(query.get('scene')||'daily');if(query.get('page'))go(query.get('page'),true);

function usageDetails(){showSheet(`${sheetHeading("今天的使用节奏","工作电脑 · Input Monitor")}<div class="receipt"><div class="receipt-row"><span>活跃时间</span><strong>2 小时 18 分</strong></div><div class="receipt-row"><span>键盘输入</span><strong>3,284 次</strong></div><div class="receipt-row"><span>鼠标点击</span><strong>1,206 次</strong></div><div class="receipt-row"><span>使用最多的应用</span><strong>Code · 1 小时 12 分</strong></div></div><p class="note">示例数据。统计在设备本地处理，手机访问需获得授权。</p><button class="primary" onclick="closeSheet()">完成</button>`,"输入活动统计")}

function sceneMenu(){showSheet(`${sheetHeading("选择演示场景","这些选项只用于体验原型。")}<div class="list-card">${[["daily","日常使用"],["send","发一份文件"],["offline","电脑不在线"],["first","第一次打开"]].map(([id,label])=>row("arrow",label,"点击开始体验",`scenario('${id}')`)).join("")}</div>`,"原型场景")}

function prototypeInfo(){showSheet(`${sheetHeading("关于这份交互原型")}<p class="notification-body">这里展示 MPT 的理想手机体验。设备、文件与状态均为示例，不会实际传输文件或控制电脑。</p><p class="notification-body">现有 Android 已接入文件互传、通知和 SSH 模块。电脑工具遥控、扫码配对及自动网盘转交属于拟议体验，仍需接入原有权限与运行机制。</p><button class="primary bottom-space" onclick="closeSheet()">继续体验</button>`,"原型说明")}
