<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <PackageId>MyPowerTools.UI.Testing</PackageId>
    <Version>0.2.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyPowerTools.UI.Primitives\MyPowerTools.UI.Primitives.csproj" />
    <ProjectReference Include="..\MyPowerTools.Packaging\MyPowerTools.Packaging.csproj" />
  </ItemGroup>
</Project>
