const paths={chat:'M5 4h14v11H9l-4 4V4Z',contacts:'M4 3h16v18H4z M2 7h4 M2 12h4 M2 17h4 M9 16c0-4 7-4 7 0 M14 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0',pc:'M3 4h18v12H3z M8 21h8 M12 16v5',mac:'M5 3h14v13H5z M2 20h20l-3-4H5z',phone:'M7 2h10v20H7z M10 18h4',shared:'M3 5h18v14H3z M3 10h5l2 3h4l2-3h5',gear:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z',back:'m14 5-7 7 7 7',more:'M5 12h.01 M12 12h.01 M19 12h.01',file:'M5 2h9l5 5v15H5z M14 2v6h5 M8 13h8 M8 17h6',plus:'M12 4v16 M4 12h16',check:'m5 12 4 4L19 6'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.pc}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let devices,threads,drafts,active='shared',currentTab='chats',offline=false,policy='auto',mobileData=true,staged=[],forwardItem=null,generation=0;
function seed(){devices=[{id:'shared',name:'文件传输助手',kind:'shared',sub:'所有已加入的设备',member:true},{id:'imac',name:'LIS-IMAC',kind:'pc',sub:'Windows · 工作电脑',member:true},{id:'mac',name:'MacBook Air',kind:'mac',sub:'macOS · 随身电脑',member:true},{id:'studio',name:'工作室电脑',kind:'pc',sub:'Windows · 暂未连接',member:false,asleep:true}];threads={shared:[{text:'这版方案放在这里，回家用电脑继续。',sender:'我的手机',mine:true,status:'已同步 · 1 台设备已接收'},{text:'产品方案.pdf',file:true,size:'2.4 MB',sender:'LIS-IMAC',mine:false,status:'已接收'}],imac:[{text:'发我一下刚才的导出文件。',sender:'LIS-IMAC',mine:false,status:'10:28'},{text:'项目导出.zip',file:true,size:'18.6 MB',mine:true,status:'已送达'}],mac:[{text:'会议记录.md',file:true,size:'12 KB',mine:false,sender:'MacBook Air',status:'已接收'}],studio:[]};drafts={};staged=[];active='shared';currentTab='chats';offline=false;generation++}
function avatar(d){return `<span class="avatar ${d.kind}">${icon(d.kind)}</span>`}
function entry(d,sub,click){return `<button class="entry ${active===d.id&&currentTab==='chats'?'selected':''}" onclick="${click}">${avatar(d)}<span class="entrycopy"><b>${esc(d.name)}</b><small>${esc(sub)}</small></span>${currentTab==='chats'?'<span class="entrytime">10:32</span>':'<span style="color:#a1a9b5">›</span>'}</button>`}
function renderList(){let q=document.getElementById('search').value.toLowerCase();let ds=devices.filter(d=>d.name.toLowerCase().includes(q));document.getElementById('listTitle').textContent=currentTab==='chats'?'会话':'通讯录';document.getElementById('search').placeholder=currentTab==='chats'?'搜索会话':'搜索设备';document.getElementById('navchats').classList.toggle('on',currentTab==='chats');document.getElementById('navcontacts').classList.toggle('on',currentTab==='contacts');let html='';if(currentTab==='contacts'){html=`<button class="entry" onclick="addDevice()"><span class="avatar shared">${icon('plus')}</span><span class="entrycopy"><b>添加设备</b><small>扫码或粘贴连接码</small></span></button><div class="sectionlabel">共享空间</div>`;html+=ds.filter(d=>d.id==='shared').map(d=>entry(d,'查看成员与共享范围',`openChat('shared')`)).join('');html+='<div class="sectionlabel">我的设备 · '+ds.filter(d=>d.id!=='shared').length+'</div>';html+=ds.filter(d=>d.id!=='shared').map(d=>entry(d,d.sub,`profile('${d.id}')`)).join('')}else{html='<div class="sectionlabel">置顶</div>';html+=ds.filter(d=>d.id==='shared').map(d=>entry(d,preview(d.id),`openChat('${d.id}')`)).join('');html+='<div class="sectionlabel">最近会话</div>';html+=ds.filter(d=>d.id!=='shared'&&(threads[d.id]?.length||drafts[d.id]?.text)).map(d=>entry(d,preview(d.id),`openChat('${d.id}')`)).join('')}document.getElementById('list').innerHTML=html||'<p class="center">没有找到设备</p>'}
function preview(id){if(drafts[id]?.text)return '[草稿] '+drafts[id].text;let last=threads[id]?.at(-1);return last?(last.file?'[文件] ':'')+last.text:'尚无消息'}
function tab(t){saveDraft();currentTab=t;document.getElementById('search').value='';document.getElementById('prototype').classList.remove('chatopen');renderList()}
function saveDraft(){let input=document.getElementById('message');if(input)drafts[active]={text:input.value,files:staged.slice()}}
function openChat(id){saveDraft();active=id;staged=(drafts[id]?.files||[]).slice();currentTab='chats';closeSheet();document.getElementById('prototype').classList.add('chatopen');renderList();renderChat()}
function renderChat(){const d=devices.find(d=>d.id===active);document.getElementById('conversation').innerHTML=`<header class="chathead"><button class="iconbtn back" aria-label="返回会话" onclick="tab('chats')">${icon('back')}</button>${avatar(d)}<div class="titles"><h3>${esc(d.name)}</h3><p>${d.id==='shared'?'共享会话 · '+(devices.filter(x=>x.member&&x.id!=='shared').length+1)+' 台设备':'仅你与这台设备可见'}</p></div><button class="iconbtn" aria-label="会话详情" onclick="${d.id==='shared'?'members()':`profile('${d.id}')`}">${icon('more')}</button></header>${offline?'<div class="banner">当前无网络，消息会保留并在连接恢复后发送。</div>':''}<div class="thread" id="thread"></div><div class="composer"><div id="attachments" class="attachments"></div><div class="composerrow"><button class="iconbtn" aria-label="添加附件" onclick="attach()">${icon('plus')}</button><textarea id="message" aria-label="消息内容" placeholder="写点什么…" rows="1" oninput="draftChanged()" onkeydown="if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();send()}">${esc(drafts[active]?.text||'')}</textarea><button class="send" id="send" onclick="send()">发送</button></div><div class="composerhint">Enter 换行 · Ctrl / ⌘ + Enter 发送</div></div>`;renderMessages();renderAttachments()}
function renderMessages(){const el=document.getElementById('thread');if(!el)return;const msgs=threads[active]||[];el.innerHTML='<div class="date">今天 · 10:32</div>'+(!msgs.length?'<div class="center" style="padding-top:90px"><h3>开始和这台设备聊天</h3><p style="color:var(--muted);font-size:12px;margin-top:10px">文字、照片和文件，都可以直接发过来。</p></div>':'')+msgs.map((m,i)=>`<div class="msg ${m.mine?'mine':''}">${!m.mine?`<div class="sender">${esc(m.sender)}</div>`:''}<button class="bubble" onclick="messageDetails(${i})">${m.file?`<span class="file"><span class="filemark">${esc(m.text.split('.').at(-1).slice(0,4).toUpperCase())}</span><span class="filename"><b>${esc(m.text)}</b><small>${esc(m.size)} · ${m.mine?'文件':'点按查看'}</small></span></span>`:esc(m.text)}</button><button class="receipt" onclick="messageDetails(${i})">${esc(m.status)}</button></div>`).join('');el.scrollTop=el.scrollHeight;renderList()}
function draftChanged(){saveDraft();document.getElementById('send').disabled=!document.getElementById('message').value.trim()&&!staged.length;renderList()}
function renderAttachments(){document.getElementById('attachments').innerHTML=staged.map((f,i)=>`<div class="attachment">${icon('file')}<span>${esc(f.name)}</span><button aria-label="移除附件" onclick="staged.splice(${i},1);saveDraft();renderAttachments()">×</button></div>`).join('');draftChanged()}
function sheet(title,body){let el=document.getElementById('overlay');el.hidden=false;el.innerHTML=`<section class="sheet" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="sheethead"><h3>${esc(title)}</h3><button class="iconbtn" aria-label="关闭" onclick="closeSheet()">×</button></div>${body}</section>`;el.querySelector('button')?.focus()}
function closeSheet(){document.getElementById('overlay').hidden=true}
function toast(t){let el=document.getElementById('toast');el.textContent=t;el.hidden=false;setTimeout(()=>el.hidden=true,2400)}
function attach(){saveDraft();sheet('添加到消息',`<p>选中后先放入待发区，点击发送才开始传输。</p><button class="entry" onclick="addSample()"><span class="avatar shared">${icon('file')}</span><span class="entrycopy"><b>添加示例文件</b><small>项目资料.pdf · 2.4 MB</small></span></button><label class="secondary" style="display:block;text-align:center;cursor:pointer">选择本地文件（只演示名称）<input type="file" multiple hidden onchange="selectFiles(this.files)"></label><p style="margin-top:15px">本网页不会读取或上传文件内容。</p>`)}
function addSample(){staged.push({name:'项目资料.pdf',size:'2.4 MB'});closeSheet();saveDraft();renderAttachments()}
function selectFiles(fs){Array.from(fs).forEach(f=>staged.push({name:f.name,size:(f.size/1048576).toFixed(1)+' MB'}));closeSheet();saveDraft();renderAttachments()}
function send(){let text=document.getElementById('message').value.trim();if(!text&&!staged.length)return;let batch=[];if(text)batch.push({text,mine:true});batch.push(...staged.map(f=>({text:f.name,file:true,size:f.size,mine:true})));const id=active;threads[id]??=[];batch.forEach(m=>{m.status='等待发送';threads[id].push(m);deliver(m,id)});staged=[];drafts[id]={text:'',files:[]};document.getElementById('message').value='';renderAttachments();renderMessages()}
function deliver(m,id){if(offline){m.status='等待网络 · 已保留';return}const g=generation;m.status='发送中 0%';[35,76,100].forEach((p,i)=>setTimeout(()=>{if(g!==generation||offline||m.cancelled)return;m.status=p<100?'发送中 '+p+'%':id==='shared'?'已同步':devices.find(d=>d.id===id)?.asleep?'已暂存 · 等待设备接收':'已送达';if(id===active)renderMessages();else renderList()},(i+1)*650))}
function toggleNetwork(){saveDraft();offline=!offline;document.getElementById('network').textContent=offline?'恢复网络':'模拟断网';if(offline)Object.values(threads).flat().filter(m=>m.status.startsWith('发送中')).forEach(m=>m.status='等待网络 · 已保留');else Object.entries(threads).forEach(([id,ms])=>ms.filter(m=>m.status.startsWith('等待网络')).forEach(m=>deliver(m,id)));renderChat();toast(offline?'演示：已断网，仍可输入和发送':'演示：网络恢复，队列自动继续')}
function profile(id){const d=devices.find(x=>x.id===id);sheet('设备',`<div class="center">${avatar(d)}<h3>${esc(d.name)}</h3><p>${esc(d.sub)}</p></div><div class="detailrow"><span>允许文件互传</span><span class="pill">已添加</span></div><div class="detailrow"><span>共享会话</span><small>${d.member?'已加入文件传输助手':'未加入'}</small></div><p style="margin-top:14px">私聊只发给这台设备。设备暂未连接时也可以发送，内容会先保留。</p><button class="primary" onclick="openChat('${id}')">发消息</button>${!d.member?`<button class="secondary" onclick="invite('${id}')">邀请加入文件传输助手</button>`:''}`)}
function members(){sheet('文件传输助手',`<p>这里是已加入设备的共享会话。发送的内容对成员可见，不会公开给整个网络。</p><div class="detailrow"><span>我的手机</span><small>本机</small></div>${devices.filter(d=>d.member&&d.id!=='shared').map(d=>`<div class="detailrow"><span>${esc(d.name)}</span><small>已加入</small></div>`).join('')}<button class="primary" onclick="inviteList()">邀请设备</button><p style="margin-top:15px">私聊内容不会出现在这里。邀请页面会再次说明历史消息的共享范围。</p>`)}
function inviteList(){sheet('邀请到共享会话','<p>只有确认加入后，设备才能读取此会话。</p>'+devices.filter(d=>d.id!=='shared'&&!d.member).map(d=>entry(d,d.sub,`invite('${d.id}')`)).join('')+'<button class="secondary" onclick="addDevice()">先添加一台设备</button>')}
function invite(id){const d=devices.find(d=>d.id===id);sheet('确认共享范围',`<p>邀请 <b>${esc(d.name)}</b> 加入“文件传输助手”。该设备确认加入后，可以读取共享会话中仍保留的历史和以后发送的内容。</p><p>各设备的私聊、远程控制权限不随此次邀请共享。</p><button class="primary" onclick="inviteSent('${id}')">发送邀请</button>`)}
function inviteSent(id){sheet('等待设备确认',`<p>已向 ${esc(devices.find(d=>d.id===id).name)} 发送邀请。对方确认之前不会获得共享会话权限。</p><button class="secondary" onclick="devices.find(d=>d.id==='${id}').member=true;renderChat();members();toast('演示：对方已确认加入')">演示：对方确认加入</button>`)}
function addDevice(){sheet('添加设备',`<p>在另一台设备打开 MyPowerTools，用连接码添加到通讯录。无需先连接 Tailscale。</p><button class="entry" onclick="pairPreview()"><span class="avatar shared">${icon('phone')}</span><span class="entrycopy"><b>扫描连接码</b><small>演示扫码后的确认页</small></span></button><label class="field">或粘贴连接码<textarea id="code" placeholder="粘贴设备连接码…"></textarea></label><button class="primary" onclick="if(document.getElementById('code').value.trim())pairPreview();else toast('请粘贴连接码，或点上方演示扫码')">预览设备</button><button class="secondary" onclick="sheet('我的连接码','<p>正式产品在此离线生成可扫描的设备连接码。本稿不生成真实凭据。</p><p>用途：添加文件互传联系人。不会授权远程控制或共享全部历史。</p>')">让对方添加我</button>`)}
function pairPreview(){sheet('确认添加',`<div class="center"><span class="avatar phone">${icon('phone')}</span><h3>Pixel 9</h3><p>Android · 设备标识 …a921</p></div><div class="detailrow"><span>文件互传</span><span class="pill">将允许</span></div><p style="margin-top:16px">仅加入通讯录。不会加入共享会话，也不会获得控制电脑的权限。</p><button class="primary" onclick="confirmPair()">添加到通讯录</button>`)}
function confirmPair(){if(!devices.some(d=>d.id==='pixel')){devices.push({id:'pixel',name:'Pixel 9',kind:'phone',sub:'Android · 新添加设备',member:false});threads.pixel=[]}currentTab='contacts';renderList();profile('pixel');toast('已添加，可以开始私聊')}
function messageDetails(i){let m=threads[active][i];sheet(m.file?'文件详情':'消息详情',`<p>${esc(m.text)}</p><div class="detailrow"><span>发送范围</span><small>${esc(devices.find(d=>d.id===active).name)}</small></div><div class="detailrow"><span>当前状态</span><small>${esc(m.status)}</small></div>${active==='shared'&&m.status.includes('同步')?'<h4 class="subheading">接收情况（模拟）</h4><div class="detailrow"><span>LIS-IMAC</span><small>已接收</small></div><div class="detailrow"><span>MacBook Air</span><small>等待接收</small></div>':''}<button class="secondary" onclick="forward(${i})">转发到另一段会话</button>${m.file?'<button class="secondary" onclick="toast(\'交互演示：正式产品调用系统查看器\')">打开文件</button>':''}${m.status.startsWith('等待')||m.status.startsWith('发送中')?`<button class="secondary" onclick="threads[active][${i}].cancelled=true;threads[active][${i}].status='已取消';closeSheet();renderMessages()">取消发送</button>`:''}<details style="margin-top:20px;font-size:11px;color:var(--muted)"><summary>传输详情</summary><p style="margin-top:10px">示例路径：自动选择 → 默认公网中转。直连 / Tailscale / OpenList 是后台可替换路径，不影响这段会话。真实产品只展示已观测的路径。</p></details>`)}
function forward(i){forwardItem={...threads[active][i]};sheet('转发到',devices.map(d=>entry(d,d.id==='shared'?'所有共享成员可见':'设备私聊',`forwardTo('${d.id}')`)).join(''))}
function forwardTo(id){let m=forwardItem;sheet('确认转发',`<p>${esc(m.text)}</p><div class="detailrow"><span>接收方</span><b>${esc(devices.find(d=>d.id===id).name)}</b></div><button class="primary" onclick="completeForward('${id}')">转发</button>`)}
function completeForward(id){saveDraft();let m={...forwardItem,mine:true,status:'等待发送',cancelled:false};threads[id]??=[];threads[id].push(m);openChat(id);deliver(m,id);renderMessages()}
function settings(){sheet('传输与存储',`<p>平时只需选择会话。这里决定后台怎样使用网络与存储。</p><label class="choice"><input name="policy" type="radio" value="auto" ${policy==='auto'?'checked':''}><span>自动选择<small>可用直连优先；不可达时使用默认公网中转。</small></span></label><label class="choice"><input name="policy" type="radio" value="cloud" ${policy==='cloud'?'checked':''}><span>优先使用我的网盘<small>通过 OpenList 接入网盘，减少自建中转流量。</small></span></label><label class="choice"><input name="policy" type="radio" value="private" ${policy==='private'?'checked':''}><span>仅使用我的私有存储<small>不可用时保留队列，不自动上传到默认公网。</small></span></label><label class="choice"><input id="mobileData" type="checkbox" ${mobileData?'checked':''}><span>移动网络下，大文件点按后下载<small>仍接收文字和文件通知。</small></span></label><button class="primary" onclick="savePolicy()">保存偏好</button><p style="margin-top:12px">此处仅保存原型内偏好，不会修改真实网络或网盘配置。</p>`)}
function savePolicy(){policy=document.querySelector('input[name=policy]:checked').value;mobileData=document.getElementById('mobileData').checked;if(policy!=='auto'){sheet('连接我的网盘','<p>首次选择此策略需要完成 OpenList / 网盘授权。正式产品会保留既有实例；没有实例时提供托管安装，再由你授权网盘。</p><button class="primary" onclick="closeSheet();toast(\'演示：网盘已授权，偏好已保存\')">演示：完成网盘授权</button>')}else{closeSheet();toast('演示偏好已保存')}}
function size(mode){document.getElementById('prototype').classList.toggle('phone',mode==='phone');document.getElementById('phoneMode').classList.toggle('active',mode==='phone');document.getElementById('desktopMode').classList.toggle('active',mode==='desktop');if(mode==='phone')document.getElementById('prototype').classList.remove('chatopen')}
function reset(){seed();document.getElementById('network').textContent='模拟断网';document.getElementById('search').value='';closeSheet();renderList();renderChat();document.getElementById('prototype').classList.remove('chatopen');toast('演示已重置')}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSheet()});document.getElementById('navchats').innerHTML=icon('chat');document.getElementById('navcontacts').innerHTML=icon('contacts');document.getElementById('settingsIcon').innerHTML=icon('gear');seed();renderList();renderChat();if(new URLSearchParams(location.search).get('mode')==='phone')size('phone');if(new URLSearchParams(location.search).get('chat'))openChat(new URLSearchParams(location.search).get('chat'));document.documentElement.dataset.screenshotReady='true';

function systemShare(){saveDraft();sheet('发送到哪个会话？','<p>来自系统分享：出差资料.pdf · 4.8 MB</p>'+devices.map(d=>entry(d,d.id==='shared'?'共享会话 · 成员可见':'私聊 · 仅这台设备可见',`acceptShare('${d.id}')`)).join(''))}
function acceptShare(id){openChat(id);staged.push({name:'出差资料.pdf',size:'4.8 MB'});saveDraft();renderAttachments();toast('已放入待发区，确认后点发送')}
if(new URLSearchParams(location.search).get('tab')==='contacts')tab('contacts');
