<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MyPowerTools</AssemblyName>
    <ApplicationIcon Condition="'$(OS)' == 'Windows_NT'">..\..\assets\MyPowerTools.ico</ApplicationIcon>
    <PublishAot>false</PublishAot>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <InvariantGlobalization>true</InvariantGlobalization>
    <OptimizationPreference>Speed</OptimizationPreference>
    <StripSymbols>true</StripSymbols>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <EventSourceSupport>false</EventSourceSupport>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\assets\MyPowerTools.ico" Link="MyPowerTools.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyPowerTools.Abstractions\MyPowerTools.Abstractions.csproj" />
  </ItemGroup>

</Project>
