<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ImeManager.Core</AssemblyName>
    <RootNamespace>ImeManager.MyPowerTools</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MyPowerTools.Tests" />
    <InternalsVisibleTo Include="ImeManager.Tests" />
  </ItemGroup>
</Project>
